# -*- coding: utf-8 -*-
"""finalNotebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A1N9JTz0rsYX74UQcSNGVyt3zzzRiT4r

#Bước 1: Thiết lập Môi trường & Tải Thư viện

##1.1. Cài đặt các Thư viện cần thiết
"""

# Cài đặt LightGBM và KerasTuner (nếu cần cho các bước sau)
!pip install lightgbm keras-tuner -q

print("Đã cài đặt thư viện LightGBM và KerasTuner.")

!pip install lime

"""##1.2. Import Thư viện"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import time
import os
import joblib

# Thư viện tiền xử lý
from sklearn.model_selection import train_test_split, learning_curve, GridSearchCV
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

# Thư viện Mô hình
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier
import lightgbm as lgb
from sklearn.neighbors import KNeighborsClassifier

# Thư viện Deep Learning
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization, Conv1D, MaxPooling1D, Flatten
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.optimizers import Adam
import keras_tuner as kt

# Thư viện Đánh giá & Giải thích
from sklearn.metrics import accuracy_score, classification_report, ConfusionMatrixDisplay
import lime
import lime.lime_tabular

# Cài đặt Seaborn cho biểu đồ đẹp
sns.set_theme(style="whitegrid")

print("Đã import tất cả các thư viện cần thiết.")

"""#Bước 2: Tải và Khám phá Dữ liệu (EDA)

##2.1. Kết nối Drive và Tải Dữ liệu
"""

from google.colab import drive
drive.mount('/content/drive')

# --- HÃY THAY ĐỔI ĐƯỜNG DẪN NÀY ---
file_path = '/content/drive/MyDrive/UIT/Năm 3/HK1/PTDLKD/E-Commerce Customer Data.csv' # Ví dụ đường dẫn

try:
    df = pd.read_csv(file_path)
    print(f"Tải dữ liệu thành công! Có {df.shape[0]} hàng và {df.shape[1]} cột.")
except FileNotFoundError:
    print(f"LỖI: Không tìm thấy tệp tại đường dẫn: {file_path}")

# In 5 hàng đầu tiên và thông tin
if 'df' in locals():
    print("\n--- 5 hàng dữ liệu mẫu (Thô) ---")
    print(df.head())
    print("\n--- Thông tin (Dtypes và Dữ liệu thiếu) ---")
    df.info()

"""##2.2. Trực quan hóa Biến Mục tiêu (Customer_Satisfaction)"""

if 'df' in locals():
    plt.figure(figsize=(12, 6))
    sns.countplot(data=df, x='Customer_Satisfaction', palette='viridis')
    plt.title('Phân bổ Mức độ Hài lòng GỐC (1-10)', fontsize=16)
    plt.xlabel('Điểm Hài lòng')
    plt.ylabel('Số lượng Khách hàng')

    # Đánh dấu "Vùng nhiễu"
    plt.axvspan(2.5, 6.5, color='red', alpha=0.1, label='Vùng "Nhiễu" (4-7 điểm)')
    plt.legend()
    plt.show()

"""##2.3. Trực quan hóa các Biến Số (Numeric)

Xem xét phân bổ của Age, Purchase_Amount, Return_Rate.
"""

if 'df' in locals():
    numeric_cols = ['Age', 'Purchase_Amount', 'Return_Rate', 'Time_to_Decision']

    fig, axes = plt.subplots(2, 2, figsize=(16, 10))
    fig.suptitle('Phân bổ các Biến Số Quan trọng', fontsize=18)

    sns.histplot(df, x='Age', kde=True, ax=axes[0, 0], color='skyblue')
    axes[0, 0].set_title('Phân bổ Tuổi')

    sns.histplot(df, x='Purchase_Amount', kde=True, ax=axes[0, 1], color='salmon')
    axes[0, 1].set_title('Phân bổ Số tiền Mua hàng')

    sns.histplot(df, x='Return_Rate', kde=True, ax=axes[1, 0], color='lightgreen')
    axes[1, 0].set_title('Phân bổ Tỷ lệ Trả hàng')

    sns.histplot(df, x='Time_to_Decision', kde=True, ax=axes[1, 1], color='gold')
    axes[1, 1].set_title('Phân bổ Thời gian Quyết định')

    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    plt.show()

"""##2.4. Ma trận Tương quan (Correlation Heatmap)"""

if 'df' in locals():
    # Chỉ chọn các cột số để tính tương quan
    numeric_df = df.select_dtypes(include=np.number)

    plt.figure(figsize=(14, 10))
    heatmap = sns.heatmap(numeric_df.corr(), annot=True, fmt=".2f", cmap='coolwarm', linewidths=.5)
    plt.title('Ma trận Tương quan giữa các Biến Số', fontsize=16)
    plt.show()

"""##2.5. Phân tích Chéo (Biến vs Mục tiêu)"""

if 'df' in locals():
    fig, axes = plt.subplots(1, 2, figsize=(18, 7))

    # Biểu đồ 1: Tình trạng Giao hàng
    sns.countplot(data=df, x='Delivery_Status', hue='Customer_Satisfaction', ax=axes[0], palette='coolwarm')
    axes[0].set_title('Tình trạng Giao hàng vs Mức độ Hài lòng')

    # Biểu đồ 2: Tỷ lệ Trả hàng (chỉ so 0.0 vs 1.0 cho rõ)
    df_return_sample = df[df['Return_Rate'].isin([0.0, 1.0])]
    sns.countplot(data=df_return_sample, x='Return_Rate', hue='Customer_Satisfaction', ax=axes[1], palette='Spectral')
    axes[1].set_title('Tỷ lệ Trả hàng (0.0 vs 1.0) vs Mức độ Hài lòng')

    plt.tight_layout()
    plt.show()

observations_text = """
### 1. Phân bổ Mức độ Hài lòng GỐC (1-10):
*   Biểu đồ cho thấy mức độ hài lòng của khách hàng trải dài từ 1 đến 10. Có thể thấy một sự phân bổ tương đối đồng đều với một số đỉnh và đáy.
*   **'Vùng Nhiễu' (4-7 điểm)** được đánh dấu, điều này cho thấy có một lượng lớn khách hàng có mức độ hài lòng trung tính hoặc không rõ ràng, đây có thể là một điểm cần chú ý để cải thiện trải nghiệm hoặc thu thập phản hồi rõ ràng hơn.

### 2. Phân bổ các Biến Số Quan trọng (Tuổi, Số tiền Mua hàng, Tỷ lệ Trả hàng, Thời gian Quyết định):
*   **Tuổi**: Phân bổ có vẻ tương đối chuẩn, cho thấy một sự phân bố tuổi khá rộng của khách hàng.
*   **Số tiền Mua hàng**: Có xu hướng lệch phải, cho thấy phần lớn các giao dịch có giá trị nhỏ, và một số ít giao dịch có giá trị lớn.
*   **Tỷ lệ Trả hàng**: Có thể thấy sự tập trung ở các giá trị thấp (khách hàng ít trả hàng) và một số đỉnh khác, cho thấy một số khách hàng có tỷ lệ trả hàng cao hơn.
*   **Thời gian Quyết định**: Phân bổ cho thấy thời gian trung bình khách hàng cần để đưa ra quyết định mua hàng, cần xem xét chi tiết hơn để xác định các yếu tố ảnh hưởng.

### 3. Phân bổ các Biến Phân loại (Tình trạng Giao hàng, Giới tính, Kênh Mua hàng, Sử dụng Giảm giá):
*   **Tình trạng Giao hàng**: Phần lớn đơn hàng được 'Delivered' (Đã giao), nhưng cũng có một lượng đáng kể 'Returned' (Đã trả lại) và 'Pending' (Đang chờ xử lý). Tỷ lệ trả lại hàng là một yếu tố quan trọng ảnh hưởng đến sự hài lòng.
*   **Giới tính**: Cho thấy sự phân bổ giữa nam và nữ trong tập dữ liệu, có thể có sự chênh lệch nhẹ.
*   **Kênh Mua hàng**: Phân bổ cho thấy khách hàng ưa chuộng một số kênh mua hàng nhất định hơn các kênh khác.
*   **Sử dụng Giảm giá**: Biểu đồ hiển thị tỷ lệ khách hàng có/không sử dụng giảm giá, điều này có thể liên quan đến hành vi mua hàng và độ nhạy cảm về giá.

### 4. Ma trận Tương quan giữa các Biến Số:
*   Biểu đồ này rất quan trọng để xác định các mối quan hệ tuyến tính giữa các biến số.
*   Các giá trị gần 1 hoặc -1 cho thấy mối tương quan mạnh mẽ (tích cực hoặc tiêu cực), trong khi các giá trị gần 0 cho thấy ít hoặc không có mối tương quan tuyến tính.
*   Cần kiểm tra kỹ các cặp biến có tương quan cao để hiểu rõ hơn về cách chúng ảnh hưởng lẫn nhau.

### 5. Tình trạng Giao hàng vs Mức độ Hài lòng và Tỷ lệ Trả hàng vs Mức độ Hài lòng:
*   **Tình trạng Giao hàng vs Mức độ Hài lòng**: Biểu đồ này giúp chúng ta thấy rõ mối liên hệ giữa trạng thái giao hàng và mức độ hài lòng. Có thể thấy khách hàng có xu hướng hài lòng hơn với các đơn hàng 'Delivered' và ít hài lòng hơn với các đơn hàng 'Returned' hoặc 'Pending'.
*   **Tỷ lệ Trả hàng (0.0 vs 1.0) vs Mức độ Hài lòng**: Biểu đồ này so sánh mức độ hài lòng của khách hàng không trả hàng (Return_Rate = 0.0) và khách hàng có trả hàng (Return_Rate = 1.0). Rõ ràng, khách hàng có Return_Rate = 0.0 thường có mức độ hài lòng cao hơn đáng kể so với những người có Return_Rate = 1.0.
"""

file_name = 'customer_satisfaction_observations.txt'
with open(file_name, 'w', encoding='utf-8') as f:
    f.write(observations_text)

print(f"Đã lưu nhận xét vào tệp '{file_name}' thành công.")

"""#Bước 3: Thí nghiệm 1 (Baseline - Không bỏ 4-5-6)

##3.1. Tiền xử lý (Mốc 5/6)
"""

if 'df' in locals():
    print("--- Bắt đầu Tiền xử lý (Chiến lược Baseline 5/6) ---")

    # 1. Lấp đầy dữ liệu bị thiếu
    df_filled_baseline = df.copy()
    for col in df_filled_baseline.select_dtypes(include='number').columns:
        df_filled_baseline[col] = df_filled_baseline[col].fillna(df_filled_baseline[col].median())
    for col in df_filled_baseline.select_dtypes(include='object').columns:
        df_filled_baseline[col] = df_filled_baseline[col].fillna(df_filled_baseline[col].mode()[0])

    # 2. TẠO MỤC TIÊU (y) - MỐC 5/6
    df_filled_baseline['Target_Satisfaction'] = df_filled_baseline['Customer_Satisfaction'].apply(lambda x: 1 if x > 5 else 0)
    y_baseline = df_filled_baseline['Target_Satisfaction']
    print(f"Đã tạo mục tiêu (y) theo mốc 5/6. Tỷ lệ 0/1:\n{y_baseline.value_counts(normalize=True)}")

    # 3. Kỹ sư Đặc trưng (Feature Engineering)
    df_filled_baseline['Time_of_Purchase'] = pd.to_datetime(df_filled_baseline['Time_of_Purchase'], errors='coerce')
    df_filled_baseline['Time_of_Purchase'] = df_filled_baseline['Time_of_Purchase'].fillna(df_filled_baseline['Time_of_Purchase'].mode()[0])
    df_filled_baseline['Purchase_Month'] = df_filled_baseline['Time_of_Purchase'].dt.month
    df_filled_baseline['Purchase_Day_of_Week'] = df_filled_baseline['Time_of_Purchase'].dt.dayofweek
    df_filled_baseline['Purchase_Hour'] = df_filled_baseline['Time_of_Purchase'].dt.hour
    df_filled_baseline['Is_Weekend'] = df_filled_baseline['Purchase_Day_of_Week'].apply(lambda x: 1 if x >= 5 else 0)

    # 4. Chọn X (Đầu vào)
    columns_to_drop = ['Customer_ID', 'Customer_Satisfaction', 'Target_Satisfaction', 'Time_of_Purchase']
    X_baseline = df_filled_baseline.drop(columns=columns_to_drop)

    # 5. Định nghĩa các cột Số và cột Chữ
    numeric_features_b = X_baseline.select_dtypes(include='number').columns
    categorical_features_b = X_baseline.select_dtypes(include='object').columns

    # 6. Tạo Bộ xử lý (Preprocessor)
    preprocessor_baseline = ColumnTransformer(
        transformers=[
            ('num', StandardScaler(), numeric_features_b),
            ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features_b)
        ],
        remainder='passthrough'
    )

    # 7. Áp dụng bộ xử lý
    X_processed_baseline = preprocessor_baseline.fit_transform(X_baseline)

    # 8. Chia Train/Test
    X_train_b, X_test_b, y_train_b, y_test_b = train_test_split(
        X_processed_baseline, y_baseline,
        test_size=0.2,
        random_state=42,
        stratify=y_baseline
    )

    print(f"\nTiền xử lý Baseline Hoàn tất.")

else:
    print("LỖI: Biến 'df' chưa được tạo. Vui lòng chạy cell 2.1 trước.")

"""##3.2. (MỚI) Kiểm tra Dữ liệu Huấn luyện Baseline"""

if 'X_train_b' in locals():
    print("--- KIỂM TRA DỮ LIỆU HUẤN LUYỆN BASELINE (Mốc 5/6) ---")

    # 1. In Shape
    print(f"Shape của X_train_b (Baseline): {X_train_b.shape}")
    print(f"Shape của y_train_b (Baseline): {y_train_b.shape}")

    # 2. In Dữ liệu mẫu
    print("\n--- 3 Dòng Dữ liệu mẫu (X_train_b) ---")
    print("(Lưu ý: Dữ liệu đã được Chuẩn hóa (scaled) và Mã hóa (encoded))")

    if not isinstance(X_train_b, np.ndarray):
        print(X_train_b.toarray()[:3])
    else:
        print(X_train_b[:3])

else:
    print("LỖI: Biến 'X_train_b' chưa được tạo. Vui lòng chạy cell 3.1.")

if 'df' in locals():
    print("--- Các cột phân loại trong dữ liệu gốc (trước One-Hot Encoding) ---")
    for col in df.select_dtypes(include='object').columns:
        if col not in ['Customer_ID', 'Time_of_Purchase']:
            unique_values = df[col].nunique()
            print(f"Cột '{col}': có {unique_values} giá trị duy nhất")

    # Lấy tên các đặc trưng đã được tạo bởi preprocessor_baseline
    # (Sử dụng preprocessor_filtered vì nó là cái đã được dùng để tạo X_train cuối cùng)
    if 'preprocessor_filtered' in locals():
        original_feature_names = preprocessor_filtered.get_feature_names_out()
        print(f"\nTổng số cột sau tiền xử lý và One-Hot Encoding: {len(original_feature_names)}")
        print("\n--- Một số tên cột mới sau One-Hot Encoding (ví dụ) ---")
        # In ra 10 cột đầu và 10 cột cuối để thấy sự thay đổi
        print(original_feature_names[:10])
        print('...')
        print(original_feature_names[-10:])
    else:
        print("LỖI: Biến 'preprocessor_filtered' không tồn tại. Vui lòng đảm bảo bạn đã chạy Bước 4.1.")
else:
    print("LỖI: Biến 'df' không tồn tại. Vui lòng chạy cell 2.1 trước.")

if 'X_train_b' in locals() and 'preprocessor_baseline' in locals():
    print("--- 3 Dòng Dữ liệu mẫu của Dataset Baseline sau Tiền xử lý và Mã hóa One-Hot ---")

    # Lấy tên các đặc trưng đã được tạo bởi preprocessor_baseline
    feature_names_baseline = preprocessor_baseline.get_feature_names_out()

    # Chuyển X_train_b thành DataFrame để hiển thị tên cột
    # X_train_b là mảng numpy, nên có thể cần toarray() nếu nó là sparse matrix
    if not isinstance(X_train_b, np.ndarray):
        X_train_b_dense = X_train_b.toarray()
    else:
        X_train_b_dense = X_train_b

    df_processed_sample_baseline = pd.DataFrame(X_train_b_dense, columns=feature_names_baseline)

    # Hiển thị 3 dòng đầu tiên
    display(df_processed_sample_baseline.head(3))
    print(f"\nTổng số cột sau tiền xử lý và One-Hot Encoding (Baseline): {df_processed_sample_baseline.shape[1]}")

else:
    print("LỖI: Biến 'X_train_b' hoặc 'preprocessor_baseline' chưa được tạo. Vui lòng chạy Bước 3.1 trước.")

"""##3.3. (MỚI) Chuẩn bị Thư mục Lưu trữ"""

# Tạo thư mục để LƯU mô hình trên Google Drive
model_save_directory = "/content/drive/MyDrive/UIT/Năm 3/HK1/PTDLKD/finalModels/"
os.makedirs(model_save_directory, exist_ok=True)
print(f"Các mô hình sẽ được lưu tại: {model_save_directory}")

# Tạo danh sách results để tổng kết cuối cùng
results = []
print("Đã tạo danh sách 'results' để tổng kết.")

"""##3.3. Huấn luyện Mô hình Baseline (LightGBM)"""

if 'X_train_b' in locals():
    print("--- Đang huấn luyện & LƯU TRỮ Mô hình Baseline (LightGBM) ---")
    start_time = time.time()

    model_baseline_lgbm = lgb.LGBMClassifier(random_state=42, verbosity=-1)
    model_baseline_lgbm.fit(X_train_b, y_train_b)

    y_pred_b = model_baseline_lgbm.predict(X_test_b)
    accuracy_baseline = accuracy_score(y_test_b, y_pred_b)
    end_time = time.time()

    # 1. (MỚI) LƯU MÔ HÌNH VÀO GOOGLE DRIVE
    model_path_baseline = os.path.join(model_save_directory, "model_baseline_LGBM_5_6.joblib")
    joblib.dump(model_baseline_lgbm, model_path_baseline)
    print(f"\nĐÃ LƯU MÔ HÌNH BASELINE tại: {model_path_baseline}")

    # 2. Lưu kết quả
    results.append({
        'Thuật toán': 'Baseline LGBM (Mốc 5/6)',
        'Độ chính xác (Accuracy)': accuracy_baseline,
        'Thời gian (giây)': end_time - start_time
    })

    print(f"\n-> Baseline LGBM (Mốc 5/6) - Độ chính xác: {accuracy_baseline*100:.2f}%")

    # 3. In Báo cáo Chi tiết
    print("\n--- Báo cáo Chi tiết (Baseline) ---")
    print(classification_report(y_test_b, y_pred_b))

    # 4. Vẽ Ma trận Nhầm lẫn
    print("--- Ma trận Nhầm lẫn (Baseline) ---")
    ConfusionMatrixDisplay.from_estimator(model_baseline_lgbm, X_test_b, y_test_b,
                                          cmap=plt.cm.Blues)
    plt.title('Ma trận Nhầm lẫn - Baseline LGBM (Mốc 5/6)')
    plt.show()

else:
    print("LỖI: Bạn cần chạy cell 3.1 và 3.2 trước.")

# 3.1. Tiền xử lý (Mốc 5/6)
# Cell 3RNxqYg368cd (Code):
# Mục đích: Cell này thực hiện các bước tiền xử lý dữ liệu quan trọng cho mô hình baseline. Các bước bao gồm lấp đầy giá trị thiếu (sử dụng median cho số và mode cho phân loại), tạo biến mục tiêu Target_Satisfaction bằng cách chia mức độ hài lòng khách hàng thành 2 lớp (1 nếu > 5, 0 nếu <= 5), kỹ thuật đặc trưng thời gian (tháng, ngày trong tuần, giờ, cuối tuần), chọn các cột đặc trưng (X_baseline) và định nghĩa bộ xử lý (ColumnTransformer) để chuẩn hóa số và mã hóa one-hot cho phân loại. Cuối cùng, dữ liệu được chia thành tập huấn luyện và kiểm tra.
# Nhận xét: Việc chia biến mục tiêu thành 0/1 với mốc 5/6 là một chiến lược quan trọng để biến bài toán dự đoán Customer_Satisfaction (từ 1-10) thành bài toán phân loại nhị phân (hài lòng/không hài lòng). Tỷ lệ 0/1 gần như cân bằng (khoảng 49% 0 và 51% 1) cho thấy tập dữ liệu khá tốt cho việc huấn luyện mô hình phân loại mà không bị lệch lớp quá nhiều. Các bước feature engineering về thời gian cũng có thể giúp mô hình nắm bắt các xu hướng theo thời gian.
# 3.2. Kiểm tra Dữ liệu Huấn luyện Baseline
# Cell v896Fm1o7F9m (Code):
# Mục đích: Cell này dùng để kiểm tra hình dạng (shape) của dữ liệu huấn luyện và kiểm tra (X_train_b, y_train_b) sau khi tiền xử lý và chia tách, cũng như hiển thị 3 dòng dữ liệu mẫu đã được xử lý (chuẩn hóa và mã hóa).
# Nhận xét: Việc kiểm tra shape xác nhận rằng dữ liệu đã được xử lý và chia tách đúng cách (10184 mẫu cho huấn luyện, 88 đặc trưng). Dữ liệu mẫu hiển thị các giá trị số đã được chuẩn hóa (có thể âm hoặc dương xung quanh 0) và các giá trị 0/1 từ mã hóa one-hot, cho thấy quá trình tiền xử lý đã diễn ra thành công.
# 3.3. Chuẩn bị Thư mục Lưu trữ
# Cell L0aP-Ntm9fdz (Code):
# Mục đích: Tạo một thư mục trên Google Drive (/content/drive/MyDrive/UIT/Năm 3/HK1/PTDLKD/models/) để lưu trữ các mô hình đã huấn luyện và khởi tạo một danh sách results trống để tổng hợp kết quả của các mô hình khác nhau.
# Nhận xét: Đây là một bước thực hành tốt để tổ chức và lưu trữ các mô hình, đảm bảo chúng có thể được tái sử dụng hoặc so sánh sau này. Danh sách results sẽ hữu ích để dễ dàng so sánh hiệu suất giữa các mô hình và thí nghiệm khác nhau.
# 3.4. Huấn luyện Mô hình Baseline (LightGBM)
# Cell H-pzCuWb7JbL (Code):
# Mục đích: Cell này huấn luyện một mô hình LGBMClassifier làm baseline. Sau khi huấn luyện, nó dự đoán trên tập kiểm tra, tính toán độ chính xác (accuracy_score), lưu mô hình vào Google Drive, ghi lại kết quả vào danh sách results, in báo cáo phân loại (classification_report) và vẽ ma trận nhầm lẫn (ConfusionMatrixDisplay).
# Nhận xét:
# Độ chính xác: Mô hình baseline đạt độ chính xác khoảng 71.33%. Đây là một điểm khởi đầu hợp lý, cho thấy mô hình có khả năng phân loại tốt hơn đáng kể so với việc đoán ngẫu nhiên (50%).
# Báo cáo phân loại: Báo cáo cung cấp các chỉ số quan trọng như precision, recall, và f1-score cho cả hai lớp (0 và 1). Điều này giúp đánh giá chi tiết hơn về hiệu suất của mô hình đối với từng lớp. Ví dụ, precision cao cho lớp 1 có nghĩa là khi mô hình dự đoán là hài lòng thì khả năng cao là đúng.
# Ma trận nhầm lẫn: Ma trận này trực quan hóa số lượng dự đoán đúng và sai cho mỗi lớp. Nó cho thấy mô hình đang nhầm lẫn giữa các lớp như thế nào (ví dụ: có bao nhiêu khách hàng thực sự không hài lòng nhưng bị dự đoán là hài lòng, và ngược lại). Việc xem xét ma trận nhầm lẫn giúp hiểu rõ hơn về các loại lỗi mà mô hình đang mắc phải.

"""#Bước 4: Thí nghiệm 2 (Chiến lược Lọc - Bỏ 4-5-6)

##4.1. Tiền xử lý (Chiến lược Lọc 75%)
"""

if 'df' in locals():
    print("--- Bắt đầu Tiền xử lý (Chiến lược Lọc 75%) ---")

    # 1. Lấp đầy dữ liệu bị thiếu
    df_filled_filtered = df.copy()
    for col in df_filled_filtered.select_dtypes(include='number').columns:
        df_filled_filtered[col] = df_filled_filtered[col].fillna(df_filled_filtered[col].median())
    for col in df_filled_filtered.select_dtypes(include='object').columns:
        df_filled_filtered[col] = df_filled_filtered[col].fillna(df_filled_filtered[col].mode()[0])

    # 2. LỌC DỮ LIỆU
    df_filtered = df_filled_filtered[
        (df_filled_filtered['Customer_Satisfaction'] <= 3) |
        (df_filled_filtered['Customer_Satisfaction'] >= 8)
    ].copy()

    print(f"Dữ liệu gốc: {len(df_filled_filtered)} hàng.")
    print(f"Dữ liệu đã lọc (chỉ giữ 1-3 và 8-10): {len(df_filtered)} hàng.")

    # 3. TẠO MỤC TIÊU (y) - MỐC 1-3 vs 8-10
    df_filtered['Target_Satisfaction'] = df_filtered['Customer_Satisfaction'].apply(lambda x: 1 if x >= 8 else 0)
    y = df_filtered['Target_Satisfaction']
    print(f"Đã tạo mục tiêu (y) Lọc. Tỷ lệ 0/1:\n{y.value_counts(normalize=True)}")

    # 4. Kỹ sư Đặc trưng (Feature Engineering)
    df_filtered['Time_of_Purchase'] = pd.to_datetime(df_filtered['Time_of_Purchase'], errors='coerce')
    df_filtered['Time_of_Purchase'] = df_filtered['Time_of_Purchase'].fillna(df_filtered['Time_of_Purchase'].mode()[0])
    df_filtered['Purchase_Month'] = df_filtered['Time_of_Purchase'].dt.month
    df_filtered['Purchase_Day_of_Week'] = df_filtered['Time_of_Purchase'].dt.dayofweek
    df_filtered['Purchase_Hour'] = df_filtered['Time_of_Purchase'].dt.hour
    df_filtered['Is_Weekend'] = df_filtered['Purchase_Day_of_Week'].apply(lambda x: 1 if x >= 5 else 0)

    # 5. Chọn X (Đầu vào)
    columns_to_drop = ['Customer_ID', 'Customer_Satisfaction', 'Target_Satisfaction', 'Time_of_Purchase']
    X = df_filtered.drop(columns=columns_to_drop)

    # 6. Định nghĩa các cột Số và cột Chữ
    numeric_features = X.select_dtypes(include='number').columns
    categorical_features = X.select_dtypes(include='object').columns

    # 7. TẠO PREPROCESSOR MỚI (Rất quan trọng)
    preprocessor_filtered = ColumnTransformer(
        transformers=[
            ('num', StandardScaler(), numeric_features),
            ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)
        ],
        remainder='passthrough'
    )

    # 8. Áp dụng bộ xử lý
    X_processed = preprocessor_filtered.fit_transform(X)

    # Chuyển sang Dạng mảng (Array) để GaussianNB chạy được
    if not isinstance(X_processed, np.ndarray):
        X_processed = X_processed.toarray()
    print(f"Xử lý xong 'X' đã lọc. Tổng số cột đầu vào (features): {X_processed.shape[1]}")

    # 9. Chia Train/Test (Đây là bộ dữ liệu chính của chúng ta)
    X_train, X_test, y_train, y_test = train_test_split(X_processed, y,
                                                        test_size=0.2,
                                                        random_state=42,
                                                        stratify=y)

    print(f"\nTiền xử lý Lọc Hoàn tất.")

else:
    print("LỖI: Biến 'df' chưa được tạo. Vui lòng chạy cell 2.1 trước.")

"""##4.2. (MỚI) Kiểm tra Dữ liệu Huấn luyện CHÍNH"""

if 'X_train' in locals():
    print("--- KIỂM TRA DỮ LIỆU HUẤN LUYỆN CHÍNH (Đã lọc 1-3 vs 8-10) ---")

    # 1. In Shape
    print(f"Shape của X_train (Chính): {X_train.shape}")
    print(f"Shape của y_train (Chính): {y_train.shape}")

    # 2. In Dữ liệu mẫu
    print("\n--- 3 Dòng Dữ liệu mẫu (X_train) ---")
    print("(Lưu ý: Dữ liệu đã được Chuẩn hóa (scaled) và Mã hóa (encoded))")

    # X_train đã được .toarray() ở cell 4.1
    print(X_train[:3])

else:
    print("LỖI: Biến 'X_train' chưa được tạo. Vui lòng chạy cell 4.1.")

"""#Bước 5: So sánh (Benchmark) các Thuật toán & Giải thích (XAI)

##5.1. Chuẩn bị LIME, Bảng Kết quả & Tên "Dấu hiệu"
"""

import lime
import lime.lime_tabular
import joblib
import os
from sklearn.model_selection import learning_curve

# 1. Định nghĩa tên các lớp (output)
class_names = ['Rất Không hài lòng (0)', 'Rất Hài lòng (1)']

# 2. Lấy tên các "dấu hiệu" (features) từ preprocessor_filtered (từ Bước 4.1)
try:
    # Lấy tên từ preprocessor MỚI (đã lọc)
    feature_names = preprocessor_filtered.get_feature_names_out()
    print(f"Đã lấy thành công {len(feature_names)} tên 'dấu hiệu' (features) từ preprocessor_filtered.")
except NameError:
    print("LỖI: Biến 'preprocessor_filtered' không tồn tại.")
    print("Vui lòng chạy lại toàn bộ cell 4.1 trước khi chạy cell này.")
except Exception as e:
    print(f"Lỗi khi lấy feature_names: {e}")

# 3. Lấy thư mục lưu trữ (đã tạo ở Bước 3.3)
if 'model_save_directory' in locals():
    print(f"Các mô hình sẽ được lưu tại: {model_save_directory}")
else:
    # Nếu chạy cell này độc lập, tạo lại thư mục
    model_save_directory = "/content/drive/MyDrive/UIT/Năm 3/HK1/PTDLKD/modles/"
    os.makedirs(model_save_directory, exist_ok=True)
    print(f"Đã tạo thư mục lưu trữ mới tại: {model_save_directory}")

# 4. Lấy danh sách 'results' (đã tạo ở Bước 3.3)
if 'results' not in locals():
    results = []
    print("Đã tạo danh sách 'results' mới.")
else:
    print("Sử dụng danh sách 'results' đã có (chứa kết quả Baseline).")

# 5. Khởi tạo "Công cụ Giải thích LIME"
# (Sử dụng X_train - bộ dữ liệu "chính" đã lọc từ Cell 4.2)
if 'X_train' in locals() and 'feature_names' in locals():
    explainer = lime.lime_tabular.LimeTabularExplainer(
        training_data=X_train,
        feature_names=feature_names,
        class_names=class_names,
        mode='classification'
    )
    print("Công cụ Giải thích LIME đã sẵn sàng!")
else:
    print("LỖI: Không thể khởi tạo LIME. Vui lòng chạy lại Bước 4.1 và 4.2.")

"""##Thuật toán 1: Hồi quy Logistic (Logistic Regression)"""

if 'X_train' in locals():
    print("--- 1. Đang huấn luyện: Hồi quy Logistic (Logistic Regression) ---")
    start_time = time.time()

    # 1. Khởi tạo và Huấn luyện
    model_lr = LogisticRegression(max_iter=1000, random_state=42)
    model_lr.fit(X_train, y_train)

    # 2. DỰ ĐOÁN VÀ ĐÁNH GIÁ
    y_pred_lr = model_lr.predict(X_test)
    accuracy_lr = accuracy_score(y_test, y_pred_lr)
    end_time = time.time()

    # 3. LƯU MÔ HÌNH VÀO GOOGLE DRIVE
    model_path_lr = os.path.join(model_save_directory, "model_logistic_regression.joblib")
    joblib.dump(model_lr, model_path_lr)
    print(f"\nĐÃ LƯU MÔ HÌNH tại: {model_path_lr}")

    # 4. Lưu kết quả
    results.append({
        'Thuật toán': 'Logistic Regression (Lọc)',
        'Độ chính xác (Accuracy)': accuracy_lr,
        'Thời gian (giây)': end_time - start_time
    })

    print(f"-> Logistic Regression - Độ chính xác: {accuracy_lr*100:.2f}% (Thời gian: {end_time - start_time:.2f}s)")

    # 5. In Báo cáo Chi tiết
    print("\n--- Báo cáo Chi tiết (Classification Report) ---")
    print(classification_report(y_test, y_pred_lr, target_names=class_names))

    # 6. Vẽ Ma trận Nhầm lẫn
    print("\n--- Ma trận Nhầm lẫn (Confusion Matrix) ---")
    ConfusionMatrixDisplay.from_estimator(model_lr, X_test, y_test,
                                          display_labels=class_names,
                                          cmap=plt.cm.Blues)
    plt.title('Ma trận Nhầm lẫn - Logistic Regression')
    plt.show()

    # 7. VẼ ĐƯỜNG CONG HỌC TẬP (Learning Curve)
    print("\n--- Đường cong Học tập (Learning Curve) ---")

    train_sizes, train_scores, test_scores = learning_curve(
        model_lr, X_train, y_train, cv=5, n_jobs=-1,
        train_sizes=np.linspace(.1, 1.0, 5) # 5 điểm (10% đến 100% dữ liệu)
    )

    train_scores_mean = np.mean(train_scores, axis=1)
    train_scores_std = np.std(train_scores, axis=1)
    test_scores_mean = np.mean(test_scores, axis=1)
    test_scores_std = np.std(test_scores, axis=1)

    plt.figure(figsize=(10, 6))
    plt.fill_between(train_sizes, train_scores_mean - train_scores_std,
                     train_scores_mean + train_scores_std, alpha=0.1, color="r")
    plt.fill_between(train_sizes, test_scores_mean - test_scores_std,
                     test_scores_mean + test_scores_std, alpha=0.1, color="g")

    plt.plot(train_sizes, train_scores_mean, 'o-', color="r", label="Điểm Huấn luyện (Train)")
    plt.plot(train_sizes, test_scores_mean, 'o-', color="g", label="Điểm Kiểm tra (Test)")

    plt.title("Đường cong Học tập - Logistic Regression")
    plt.xlabel("Số lượng Mẫu Huấn luyện")
    plt.ylabel("Điểm Accuracy")
    plt.legend(loc="best")
    plt.grid(True)
    plt.show()

else:
    print("LỖI: Bạn cần chạy Bước 4.1 và 4.2 để tạo X_train, y_train trước.")

"""Giải thích XAI (LIME) cho Logistic Regression"""

if 'explainer' in locals() and 'model_lr' in locals():
    sample_index = 10 # Chọn 1 khách hàng (ví dụ: thứ 10) để giải thích
    sample_data_row = X_test[sample_index]

    print(f"--- Bắt đầu Giải thích LIME cho Khách hàng thứ {sample_index} ---")

    explanation = explainer.explain_instance(
        data_row=sample_data_row,
        predict_fn=model_lr.predict_proba,
        num_features=10
    )

    actual_result = y_test.iloc[sample_index]
    print(f"Kết quả THỰC TẾ:      {class_names[actual_result]}")
    prediction = model_lr.predict([sample_data_row])[0]
    print(f"Dự đoán của MÔ HÌNH: {class_names[prediction]}")

    print("\n--- Lý do (Giải thích của LIME) ---")
    explanation.show_in_notebook(show_table=True, show_all=False)

else:
    print("LỖI: 'explainer' hoặc 'model_lr' chưa được tạo.")

"""##Thuật toán 2: Cây Quyết định (Decision Tree)"""

if 'X_train' in locals():
    print("--- 2. Đang huấn luyện: Cây Quyết định (Decision Tree) ---")
    start_time = time.time()

    # 1. Khởi tạo và Huấn luyện
    model_dt = DecisionTreeClassifier(random_state=42)
    model_dt.fit(X_train, y_train)

    # 2. DỰ ĐOÁN VÀ ĐÁNH GIÁ
    y_pred_dt = model_dt.predict(X_test)
    accuracy_dt = accuracy_score(y_test, y_pred_dt)
    end_time = time.time()

    # 3. LƯU MÔ HÌNH VÀO GOOGLE DRIVE
    model_path_dt = os.path.join(model_save_directory, "model_decision_tree.joblib")
    joblib.dump(model_dt, model_path_dt)
    print(f"\nĐÃ LƯU MÔ HÌNH tại: {model_path_dt}")

    # 4. Lưu kết quả
    results.append({
        'Thuật toán': 'Decision Tree (Lọc)',
        'Độ chính xác (Accuracy)': accuracy_dt,
        'Thời gian (giây)': end_time - start_time
    })

    print(f"-> Decision Tree - Độ chính xác: {accuracy_dt*100:.2f}% (Thời gian: {end_time - start_time:.2f}s)")

    # 5. In Báo cáo Chi tiết
    print("\n--- Báo cáo Chi tiết (Classification Report) ---")
    print(classification_report(y_test, y_pred_dt, target_names=class_names))

    # 6. Vẽ Ma trận Nhầm lẫn
    print("\n--- Ma trận Nhầm lẫn (Confusion Matrix) ---")
    ConfusionMatrixDisplay.from_estimator(model_dt, X_test, y_test,
                                          display_labels=class_names,
                                          cmap=plt.cm.Greens)
    plt.title('Ma trận Nhầm lẫn - Decision Tree')
    plt.show()

    # 7. VẼ ĐƯỜNG CONG HỌC TẬP (Learning Curve)
    print("\n--- Đường cong Học tập (Learning Curve) ---")

    train_sizes, train_scores, test_scores = learning_curve(
        model_dt, X_train, y_train, cv=5, n_jobs=-1,
        train_sizes=np.linspace(.1, 1.0, 5)
    )

    train_scores_mean = np.mean(train_scores, axis=1)
    train_scores_std = np.std(train_scores, axis=1)
    test_scores_mean = np.mean(test_scores, axis=1)
    test_scores_std = np.std(test_scores, axis=1)

    plt.figure(figsize=(10, 6))
    plt.fill_between(train_sizes, train_scores_mean - train_scores_std,
                     train_scores_mean + train_scores_std, alpha=0.1, color="r")
    plt.fill_between(train_sizes, test_scores_mean - test_scores_std,
                     test_scores_mean + test_scores_std, alpha=0.1, color="g")

    plt.plot(train_sizes, train_scores_mean, 'o-', color="r", label="Điểm Huấn luyện (Train)")
    plt.plot(train_sizes, test_scores_mean, 'o-', color="g", label="Điểm Kiểm tra (Test)")

    plt.title("Đường cong Học tập - Decision Tree")
    plt.xlabel("Số lượng Mẫu Huấn luyện")
    plt.ylabel("Điểm Accuracy")
    plt.legend(loc="best")
    plt.grid(True)
    plt.show()

else:
    print("LỖI: Bạn cần chạy Bước 4.1 và 4.2 để tạo X_train, y_train trước.")

"""### Nhận xét về Hồi quy Logistic (Thuật toán 1)

*   **Độ chính xác:** Đạt mức **75.81%**, cao hơn đáng kể so với mô hình Baseline (LGBM 71.33%) và Decision Tree (70.93%). Điều này cho thấy Hồi quy Logistic hoạt động hiệu quả trên tập dữ liệu đã được lọc.
*   **Báo cáo Phân loại:** Cả `precision`, `recall` và `f1-score` cho cả hai lớp 'Rất Không hài lòng (0)' và 'Rất Hài lòng (1)' đều khá cân bằng và cao (khoảng 0.74 - 0.78), cho thấy mô hình không bị thiên vị quá nhiều về một lớp nào và có khả năng phân loại tốt cả hai nhóm khách hàng.
*   **Ma trận Nhầm lẫn:** Cho thấy số lượng dự đoán đúng (True Positives, True Negatives) tương đối cao, và số lượng dự đoán sai (False Positives, False Negatives) là chấp nhận được, phù hợp với độ chính xác tổng thể.
*   **Đường cong Học tập:**
    *   Điểm huấn luyện và điểm kiểm tra khá gần nhau và có xu hướng hội tụ khi số lượng mẫu huấn luyện tăng lên. Điều này cho thấy mô hình không bị quá khớp (overfitting) và đang học tốt từ dữ liệu.
    *   Đường cong học tập ổn định, cho thấy mô hình đủ phức tạp để nắm bắt các mối quan hệ trong dữ liệu mà không cần thêm dữ liệu huấn luyện đáng kể để cải thiện thêm hiệu suất.

**Tóm lại:** Mô hình Hồi quy Logistic thể hiện hiệu suất tốt và ổn định sau khi áp dụng chiến lược lọc dữ liệu, trở thành một ứng cử viên mạnh mẽ cho bài toán này.

### Nhận xét về Cây Quyết định (Thuật toán 2)

*   **Độ chính xác:** Đạt **70.93%**, thấp hơn một chút so với mô hình Baseline LGBM (71.33%) và thấp hơn đáng kể so với Hồi quy Logistic (75.81%).
*   **Báo cáo Phân loại:** Các chỉ số `precision`, `recall`, `f1-score` cho cả hai lớp đều nằm trong khoảng 0.69 - 0.73. Mặc dù không quá tệ, nhưng chúng thấp hơn so với Hồi quy Logistic, cho thấy khả năng phân loại kém hơn một chút.
*   **Ma trận Nhầm lẫn:** Phản ánh độ chính xác thấp hơn, với số lượng dự đoán sai nhiều hơn so với Hồi quy Logistic.
*   **Đường cong Học tập:**
    *   Có sự chênh lệch rõ ràng giữa điểm huấn luyện (thường rất cao, có thể đạt 1.0) và điểm kiểm tra. Điều này thường là dấu hiệu của việc **quá khớp (overfitting)**, nghĩa là mô hình học quá kỹ dữ liệu huấn luyện và không khái quát hóa tốt trên dữ liệu mới.
    *   Điểm kiểm tra có thể ổn định hoặc chỉ tăng nhẹ sau một số lượng mẫu nhất định, trong khi điểm huấn luyện vẫn duy trì cao, củng cố nhận định về overfitting.

**Tóm lại:** Mô hình Cây Quyết định, với các thiết lập mặc định, có xu hướng quá khớp trên tập dữ liệu này, dẫn đến hiệu suất thấp hơn trên dữ liệu chưa thấy. Cần điều chỉnh siêu tham số (như `max_depth`, `min_samples_leaf`) để giảm overfitting và cải thiện khả năng khái quát hóa.
"""

if 'explainer' in locals() and 'model_dt' in locals():
    sample_index = 10
    sample_data_row = X_test[sample_index]

    print(f"--- Bắt đầu Giải thích LIME cho Khách hàng thứ {sample_index} ---")

    explanation = explainer.explain_instance(
        data_row=sample_data_row,
        predict_fn=model_dt.predict_proba,
        num_features=10
    )

    actual_result = y_test.iloc[sample_index]
    print(f"Kết quả THỰC TẾ:      {class_names[actual_result]}")
    prediction = model_dt.predict([sample_data_row])[0]
    print(f"Dự đoán của MÔ HÌNH: {class_names[prediction]}")

    print("\n--- Lý do (Giải thích của LIME) ---")
    explanation.show_in_notebook(show_table=True, show_all=False)

else:
    print("LỖI: 'explainer' hoặc 'model_dt' chưa được tạo.")

"""### Giải thích kết quả LIME cho Hồi quy Logistic

**LIME (Local Interpretable Model-agnostic Explanations)** là một kỹ thuật giải thích giúp hiểu được lý do tại sao một mô hình học máy lại đưa ra một dự đoán cụ thể cho một điểm dữ liệu duy nhất. Nó hoạt động bằng cách tạo ra một mô hình đơn giản (có thể hiểu được) xung quanh điểm dữ liệu đó.

**Cách đọc biểu đồ LIME:**

*   **Biểu đồ bên trái (Probabilities):** Thể hiện xác suất mô hình dự đoán cho từng lớp. Trong ví dụ này, nó cho thấy mô hình Logistic Regression dự đoán khách hàng thứ 10 là 'Rất Hài lòng (1)' với xác suất cao.
*   **Biểu đồ bên phải (Feature Contributions):** Đây là phần quan trọng nhất, hiển thị các yếu tố (features) có ảnh hưởng lớn nhất đến dự đoán của mô hình cho khách hàng cụ thể này:
    *   **Màu xanh lá cây:** Chỉ ra các đặc trưng đóng góp **tích cực** vào việc dự đoán lớp 'Rất Hài lòng (1)' (hoặc chống lại lớp 'Rất Không hài lòng (0)'). Tức là, giá trị của đặc trưng đó làm tăng khả năng khách hàng hài lòng.
    *   **Màu đỏ:** Chỉ ra các đặc trưng đóng góp **tiêu cực** vào việc dự đoán lớp 'Rất Hài lòng (1)' (hoặc ủng hộ lớp 'Rất Không hài lòng (0)'). Tức là, giá trị của đặc trưng đó làm giảm khả năng khách hàng hài lòng.
    *   **Độ dài của thanh:** Thể hiện **mức độ ảnh hưởng** của đặc trưng đó. Thanh càng dài, ảnh hưởng càng lớn.
    *   **Tên đặc trưng và giá trị:** Ví dụ, `cat__Marital_Status_Married = 1` hoặc `num__Age <= 30.50` cho biết chính xác đặc trưng nào và giá trị của nó đã ảnh hưởng đến dự đoán.

**Trong trường hợp của Logistic Regression:** Các hệ số (weights) của mô hình là tuyến tính, nên LIME có xu hướng phản ánh trực tiếp các hệ số này và cách chúng kết hợp với giá trị đặc trưng để đưa ra dự đoán. LIME giúp chúng ta thấy rõ những yếu tố nào (ví dụ: tuổi tác, tình trạng hôn nhân, kênh mua hàng, v.v.) đang 'đẩy' dự đoán về phía hài lòng hay không hài lòng cho một khách hàng cụ thể.

### Đánh giá cụ thể LIME cho Hồi quy Logistic và Cây Quyết định

**LIME (Local Interpretable Model-agnostic Explanations)** là một kỹ thuật giải thích giúp hiểu được lý do tại sao một mô hình học máy lại đưa ra một dự đoán cụ thể cho một điểm dữ liệu duy nhất. Nó hoạt động bằng cách tạo ra một mô hình đơn giản (có thể hiểu được) xung quanh điểm dữ liệu đó.

Đối với khách hàng mẫu được chọn (index 10) trong cả hai mô hình Hồi quy Logistic và Cây Quyết định, LIME đều dự đoán khách hàng này 'Rất Hài lòng (1)'. Dưới đây là phân tích các yếu tố chính đóng góp vào dự đoán này:

#### Hồi quy Logistic (Logistic Regression)

*   **Các yếu tố đóng góp Tích cực (làm tăng khả năng hài lòng - màu xanh lá cây):**
    *   `cat__Customer_Loyalty_Program_Member_Yes = 1`: Khách hàng là thành viên của chương trình khách hàng thân thiết.
    *   `num__Time_to_Decision <= 13.50`: Thời gian để đưa ra quyết định mua hàng khá nhanh.
    *   `cat__Marital_Status_Married = 1`: Khách hàng đã kết hôn.
    *   `num__Age <= 30.50`: Tuổi của khách hàng là 30.50 hoặc trẻ hơn.
    *   `cat__Education_Level_Some College = 1`: Trình độ học vấn ở mức cao đẳng.
    *   `cat__Engagement_with_Ads_Low = 1`: Khách hàng ít tương tác với quảng cáo.

*   **Các yếu tố đóng góp Tiêu cực (làm giảm khả năng hài lòng - màu đỏ):**
    *   `cat__Occupation_Engineer = 1`: Nghề nghiệp là Kỹ sư. Điều này có thể cho thấy một số kỳ vọng hoặc tiêu chuẩn cụ thể.
    *   `num__Return_Rate <= 0.0`: Tỷ lệ trả hàng rất thấp (hoặc bằng 0). Mặc dù thường là dấu hiệu tốt, nhưng đôi khi mô hình có thể tìm thấy mối quan hệ phức tạp hơn.

**Kết luận cho Logistic Regression:** Khách hàng này hài lòng chủ yếu nhờ vào việc họ là thành viên thân thiết, đưa ra quyết định mua hàng nhanh chóng, và một số đặc điểm nhân khẩu học khác.

#### Cây Quyết định (Decision Tree)

*   **Các yếu tố đóng góp Tích cực (làm tăng khả năng hài lòng - màu xanh lá cây):**
    *   `cat__Customer_Loyalty_Program_Member_Yes = 1`: Đây là yếu tố mạnh mẽ nhất, giống như Hồi quy Logistic, cho thấy tư cách thành viên là cực kỳ quan trọng.
    *   `cat__Marital_Status_Married = 1`: Khách hàng đã kết hôn.
    *   `num__Time_to_Decision <= 13.50`: Thời gian quyết định nhanh chóng.
    *   `num__Age <= 30.50`: Tuổi trẻ hơn.
    *   `cat__Engagement_with_Ads_Low = 1`: Khách hàng ít tương tác với quảng cáo.

*   **Các yếu tố đóng góp Tiêu cực (làm giảm khả năng hài lòng - màu đỏ):**
    *   `cat__Occupation_Engineer = 1`: Yếu tố này vẫn xuất hiện với đóng góp tiêu cực.
    *   `num__Return_Rate <= 0.0`: Tỷ lệ trả hàng thấp.

**Kết luận cho Decision Tree:** Mô hình Cây Quyết định cũng đồng thuận với các yếu tố chính mà Logistic Regression đã chỉ ra. Với Decision Tree, giải thích của LIME sẽ tìm ra các quy tắc phân nhánh cục bộ quan trọng nhất trong cây đã dẫn đến quyết định đó cho điểm dữ liệu cụ thể.

#### So sánh chung hai mô hình qua LIME:

Cả hai mô hình đều đồng thuận về các yếu tố chính thúc đẩy sự hài lòng của khách hàng cụ thể này: **là thành viên của chương trình khách hàng thân thiết, thời gian quyết định mua hàng nhanh chóng và các đặc điểm nhân khẩu học như tình trạng hôn nhân/tuổi tác**. Điều này cho thấy các đặc trưng này thực sự là những yếu tố dự đoán mạnh mẽ cho sự hài lòng của khách hàng trong trường hợp cụ thể này, bất kể sự khác biệt về cơ chế hoạt động của từng thuật toán.

### Giải thích kết quả LIME cho Cây Quyết định

Tương tự như Logistic Regression, LIME cung cấp cái nhìn cục bộ về dự đoán của mô hình Cây Quyết định cho một khách hàng cụ thể.

**Cách đọc biểu đồ LIME:**

*   **Biểu đồ bên trái (Probabilities):** Thể hiện xác suất mô hình dự đoán cho từng lớp. Với Decision Tree, dự đoán thường là một xác suất rất cao cho một lớp nào đó (gần 0 hoặc 1) vì nó là mô hình dựa trên quy tắc.
*   **Biểu đồ bên phải (Feature Contributions):** Hiển thị các đặc trưng có ảnh hưởng lớn nhất đến dự đoán của mô hình cho khách hàng này. Nguyên tắc màu sắc và độ dài thanh tương tự như Logistic Regression:
    *   **Màu xanh lá cây:** Đặc trưng làm tăng khả năng dự đoán lớp 'Rất Hài lòng (1)'.
    *   **Màu đỏ:** Đặc trưng làm giảm khả năng dự đoán lớp 'Rất Hài lòng (1)' (tức là ủng hộ lớp 'Rất Không hài lòng (0)').
    *   **Độ dài của thanh:** Mức độ ảnh hưởng của đặc trưng.

**Sự khác biệt và lưu ý cho Cây Quyết định:**

*   Cây Quyết định là mô hình dựa trên các **quy tắc phân nhánh** (if-then-else). Khi LIME giải thích một dự đoán từ Decision Tree, nó sẽ cố gắng tìm ra các quy tắc cục bộ quan trọng nhất trong cây đã dẫn đến quyết định đó cho điểm dữ liệu cụ thể. Các đặc trưng xuất hiện trong giải thích của LIME thường là những đặc trưng nằm trên đường đi từ gốc đến nút lá mà điểm dữ liệu đó rơi vào.
*   Đôi khi, giải thích của LIME cho Decision Tree có thể trông 'đứt đoạn' hơn so với mô hình tuyến tính, vì Decision Tree không nhìn vào mối quan hệ tuyến tính mà là các ngưỡng phân tách. Tuy nhiên, nó vẫn giúp chúng ta xác định được những tiêu chí chính mà Decision Tree đã sử dụng để phân loại một khách hàng cụ thể là hài lòng hay không hài lòng.

##Thuật toán 3: Rừng Ngẫu nhiên (Random Forest)
"""

if 'X_train' in locals():
    print("--- 3. Đang huấn luyện: Rừng Ngẫu nhiên (Random Forest) ---")
    start_time = time.time()

    # 1. Khởi tạo và Huấn luyện
    model_rf = RandomForestClassifier(random_state=42, n_jobs=-1) # n_jobs=-1: Dùng tất cả CPU
    model_rf.fit(X_train, y_train)

    # 2. DỰ ĐOÁN VÀ ĐÁNH GIÁ
    y_pred_rf = model_rf.predict(X_test)
    accuracy_rf = accuracy_score(y_test, y_pred_rf)
    end_time = time.time()

    # 3. LƯU MÔ HÌNH VÀO GOOGLE DRIVE
    model_path_rf = os.path.join(model_save_directory, "model_random_forest.joblib")
    joblib.dump(model_rf, model_path_rf)
    print(f"\nĐÃ LƯU MÔ HÌNH tại: {model_path_rf}")

    # 4. Lưu kết quả
    results.append({
        'Thuật toán': 'Random Forest (Lọc)',
        'Độ chính xác (Accuracy)': accuracy_rf,
        'Thời gian (giây)': end_time - start_time
    })

    print(f"-> Random Forest - Độ chính xác: {accuracy_rf*100:.2f}% (Thời gian: {end_time - start_time:.2f}s)")

    # 5. In Báo cáo Chi tiết
    print("\n--- Báo cáo Chi tiết (Classification Report) ---")
    print(classification_report(y_test, y_pred_rf, target_names=class_names))

    # 6. Vẽ Ma trận Nhầm lẫn
    print("\n--- Ma trận Nhầm lẫn (Confusion Matrix) ---")
    ConfusionMatrixDisplay.from_estimator(model_rf, X_test, y_test,
                                          display_labels=class_names,
                                          cmap=plt.cm.Oranges)
    plt.title('Ma trận Nhầm lẫn - Random Forest')
    plt.show()

    # 7. VẼ ĐƯỜNG CONG HỌC TẬP (Learning Curve)
    # Lưu ý: Vẽ learning curve cho Random Forest có thể hơi chậm
    print("\n--- Đường cong Học tập (Learning Curve) ---")

    train_sizes, train_scores, test_scores = learning_curve(
        model_rf, X_train, y_train, cv=3, n_jobs=-1, # Giảm cv xuống 3 cho nhanh
        train_sizes=np.linspace(.1, 1.0, 5)
    )

    train_scores_mean = np.mean(train_scores, axis=1)
    train_scores_std = np.std(train_scores, axis=1)
    test_scores_mean = np.mean(test_scores, axis=1)
    test_scores_std = np.std(test_scores, axis=1)

    plt.figure(figsize=(10, 6))
    plt.fill_between(train_sizes, train_scores_mean - train_scores_std,
                     train_scores_mean + train_scores_std, alpha=0.1, color="r")
    plt.fill_between(train_sizes, test_scores_mean - test_scores_std,
                     test_scores_mean + test_scores_std, alpha=0.1, color="g")

    plt.plot(train_sizes, train_scores_mean, 'o-', color="r", label="Điểm Huấn luyện (Train)")
    plt.plot(train_sizes, test_scores_mean, 'o-', color="g", label="Điểm Kiểm tra (Test)")

    plt.title("Đường cong Học tập - Random Forest")
    plt.xlabel("Số lượng Mẫu Huấn luyện")
    plt.ylabel("Điểm Accuracy")
    plt.legend(loc="best")
    plt.grid(True)
    plt.show()

else:
    print("LỖI: Bạn cần chạy Bước 4.1 và 4.2 để tạo X_train, y_train trước.")

if 'explainer' in locals() and 'model_rf' in locals():
    sample_index = 10
    sample_data_row = X_test[sample_index]

    print(f"--- Bắt đầu Giải thích LIME cho Khách hàng thứ {sample_index} ---")

    explanation = explainer.explain_instance(
        data_row=sample_data_row,
        predict_fn=model_rf.predict_proba, # Dùng hàm .predict_proba
        num_features=10
    )

    actual_result = y_test.iloc[sample_index]
    print(f"Kết quả THỰC TẾ:      {class_names[actual_result]}")
    prediction = model_rf.predict([sample_data_row])[0]
    print(f"Dự đoán của MÔ HÌNH: {class_names[prediction]}")

    print("\n--- Lý do (Giải thích của LIME) ---")
    explanation.show_in_notebook(show_table=True, show_all=False)

else:
    print("LỖI: 'explainer' hoặc 'model_rf' chưa được tạo.")

"""##Thuật toán 4: Máy Véc-tơ Hỗ trợ (SVM - Support Vector Machine)"""

if 'X_train' in locals():
    print("--- 4. Đang huấn luyện: Máy Véc-tơ Hỗ trợ (SVM) ---")
    print("Lưu ý: SVM với probability=True có thể chạy rất chậm...")
    start_time = time.time()

    # 1. Khởi tạo và Huấn luyện
    # Thêm probability=True để LIME có thể dùng .predict_proba
    # (Việc này làm SVM chạy chậm hơn nữa, nhưng là bắt buộc cho LIME)
    model_svm = SVC(random_state=42, probability=True)
    model_svm.fit(X_train, y_train)

    # 2. DỰ ĐOÁN VÀ ĐÁNH GIÁ
    y_pred_svm = model_svm.predict(X_test)
    accuracy_svm = accuracy_score(y_test, y_pred_svm)
    end_time = time.time()

    # 3. LƯU MÔ HÌNH VÀO GOOGLE DRIVE
    model_path_svm = os.path.join(model_save_directory, "model_svm.joblib")
    joblib.dump(model_svm, model_path_svm)
    print(f"\nĐÃ LƯU MÔ HÌNH tại: {model_path_svm}")

    # 4. Lưu kết quả
    results.append({
        'Thuật toán': 'SVM (Lọc)',
        'Độ chính xác (Accuracy)': accuracy_svm,
        'Thời gian (giây)': end_time - start_time
    })

    print(f"-> SVM - Độ chính xác: {accuracy_svm*100:.2f}% (Thời gian: {end_time - start_time:.2f}s)")

    # 5. In Báo cáo Chi tiết
    print("\n--- Báo cáo Chi tiết (Classification Report) ---")
    print(classification_report(y_test, y_pred_svm, target_names=class_names))

    # 6. Vẽ Ma trận Nhầm lẫn
    print("\n--- Ma trận Nhầm lẫn (Confusion Matrix) ---")
    ConfusionMatrixDisplay.from_estimator(model_svm, X_test, y_test,
                                          display_labels=class_names,
                                          cmap=plt.cm.Purples)
    plt.title('Ma trận Nhầm lẫn - SVM')
    plt.show()

    # 7. VẼ ĐƯỜNG CONG HỌC TẬP (Learning Curve)
    print("\n--- Đường cong Học tập (Learning Curve) ---")
    print("Đang vẽ Learning Curve cho SVM... (Có thể mất vài phút)")

    train_sizes, train_scores, test_scores = learning_curve(
        model_svm, X_train, y_train, cv=3, n_jobs=-1, # Giảm cv xuống 3 cho nhanh
        train_sizes=np.linspace(.1, 1.0, 5)
    )

    train_scores_mean = np.mean(train_scores, axis=1)
    train_scores_std = np.std(train_scores, axis=1)
    test_scores_mean = np.mean(test_scores, axis=1)
    test_scores_std = np.std(test_scores, axis=1)

    plt.figure(figsize=(10, 6))
    plt.fill_between(train_sizes, train_scores_mean - train_scores_std,
                     train_scores_mean + train_scores_std, alpha=0.1, color="r")
    plt.fill_between(train_sizes, test_scores_mean - test_scores_std,
                     test_scores_mean + test_scores_std, alpha=0.1, color="g")

    plt.plot(train_sizes, train_scores_mean, 'o-', color="r", label="Điểm Huấn luyện (Train)")
    plt.plot(train_sizes, test_scores_mean, 'o-', color="g", label="Điểm Kiểm tra (Test)")

    plt.title("Đường cong Học tập - SVM")
    plt.xlabel("Số lượng Mẫu Huấn luyện")
    plt.ylabel("Điểm Accuracy")
    plt.legend(loc="best")
    plt.grid(True)
    plt.show()

else:
    print("LỖI: Bạn cần chạy Bước 4.1 và 4.2 để tạo X_train, y_train trước.")

if 'explainer' in locals() and 'model_svm' in locals():
    sample_index = 10
    sample_data_row = X_test[sample_index]

    print(f"--- Bắt đầu Giải thích LIME cho Khách hàng thứ {sample_index} ---")

    explanation = explainer.explain_instance(
        data_row=sample_data_row,
        predict_fn=model_svm.predict_proba, # Dùng hàm .predict_proba
        num_features=10
    )

    actual_result = y_test.iloc[sample_index]
    print(f"Kết quả THỰC TẾ:      {class_names[actual_result]}")
    prediction = model_svm.predict([sample_data_row])[0]
    print(f"Dự đoán của MÔ HÌNH: {class_names[prediction]}")

    print("\n--- Lý do (Giải thích của LIME) ---")
    explanation.show_in_notebook(show_table=True, show_all=False)

else:
    print("LỖI: 'explainer' hoặc 'model_svm' chưa được tạo.")

"""##Thuật toán 5: Gaussian Naive Bayes"""

if 'X_train' in locals():
    print("--- 5. Đang huấn luyện: Gaussian Naive Bayes (GNB) ---")
    start_time = time.time()

    # 1. Khởi tạo và Huấn luyện
    # Dữ liệu X_train của chúng ta đã được chuyển thành "dense array" ở Bước 4.1
    # nên GaussianNB có thể chạy được.
    model_gnb = GaussianNB()
    model_gnb.fit(X_train, y_train)

    # 2. DỰ ĐOÁN VÀ ĐÁNH GIÁ
    y_pred_gnb = model_gnb.predict(X_test)
    accuracy_gnb = accuracy_score(y_test, y_pred_gnb)
    end_time = time.time()

    # 3. LƯU MÔ HÌNH VÀO GOOGLE DRIVE
    model_path_gnb = os.path.join(model_save_directory, "model_naive_bayes.joblib")
    joblib.dump(model_gnb, model_path_gnb)
    print(f"\nĐÃ LƯU MÔ HÌNH tại: {model_path_gnb}")

    # 4. Lưu kết quả
    results.append({
        'Thuật toán': 'Gaussian Naive Bayes (Lọc)',
        'Độ chính xác (Accuracy)': accuracy_gnb,
        'Thời gian (giây)': end_time - start_time
    })

    print(f"-> Gaussian Naive Bayes - Độ chính xác: {accuracy_gnb*100:.2f}% (Thời gian: {end_time - start_time:.2f}s)")

    # 5. In Báo cáo Chi tiết
    print("\n--- Báo cáo Chi tiết (Classification Report) ---")
    print(classification_report(y_test, y_pred_gnb, target_names=class_names))

    # 6. Vẽ Ma trận Nhầm lẫn
    print("\n--- Ma trận Nhầm lẫn (Confusion Matrix) ---")
    ConfusionMatrixDisplay.from_estimator(model_gnb, X_test, y_test,
                                          display_labels=class_names,
                                          cmap=plt.cm.YlGnBu)
    plt.title('Ma trận Nhầm lẫn - Gaussian Naive Bayes')
    plt.show()

    # 7. VẼ ĐƯỜNG CONG HỌC TẬP (Learning Curve)
    print("\n--- Đường cong Học tập (Learning Curve) ---")

    train_sizes, train_scores, test_scores = learning_curve(
        model_gnb, X_train, y_train, cv=5, n_jobs=-1,
        train_sizes=np.linspace(.1, 1.0, 5)
    )

    train_scores_mean = np.mean(train_scores, axis=1)
    train_scores_std = np.std(train_scores, axis=1)
    test_scores_mean = np.mean(test_scores, axis=1)
    test_scores_std = np.std(test_scores, axis=1)

    plt.figure(figsize=(10, 6))
    plt.fill_between(train_sizes, train_scores_mean - train_scores_std,
                     train_scores_mean + train_scores_std, alpha=0.1, color="r")
    plt.fill_between(train_sizes, test_scores_mean - test_scores_std,
                     test_scores_mean + test_scores_std, alpha=0.1, color="g")

    plt.plot(train_sizes, train_scores_mean, 'o-', color="r", label="Điểm Huấn luyện (Train)")
    plt.plot(train_sizes, test_scores_mean, 'o-', color="g", label="Điểm Kiểm tra (Test)")

    plt.title("Đường cong Học tập - Gaussian Naive Bayes")
    plt.xlabel("Số lượng Mẫu Huấn luyện")
    plt.ylabel("Điểm Accuracy")
    plt.legend(loc="best")
    plt.grid(True)
    plt.show()

else:
    print("LỖI: Bạn cần chạy Bước 4.1 và 4.2 để tạo X_train, y_train trước.")

if 'explainer' in locals() and 'model_gnb' in locals():
    sample_index = 10
    sample_data_row = X_test[sample_index]

    print(f"--- Bắt đầu Giải thích LIME cho Khách hàng thứ {sample_index} ---")

    explanation = explainer.explain_instance(
        data_row=sample_data_row,
        predict_fn=model_gnb.predict_proba, # Dùng hàm .predict_proba
        num_features=10
    )

    actual_result = y_test.iloc[sample_index]
    print(f"Kết quả THỰC TẾ:      {class_names[actual_result]}")
    prediction = model_gnb.predict([sample_data_row])[0]
    print(f"Dự đoán của MÔ HÌNH: {class_names[prediction]}")

    print("\n--- Lý do (Giải thích của LIME) ---")
    explanation.show_in_notebook(show_table=True, show_all=False)

else:
    print("LỖI: 'explainer' hoặc 'model_gnb' chưa được tạo.")

"""##Thuật toán 6: AdaBoost"""

if 'X_train' in locals():
    print("--- 6. Đang huấn luyện: AdaBoost ---")
    start_time = time.time()

    # 1. Khởi tạo và Huấn luyện
    model_ada = AdaBoostClassifier(random_state=42)
    model_ada.fit(X_train, y_train)

    # 2. DỰ ĐOÁN VÀ ĐÁNH GIÁ
    y_pred_ada = model_ada.predict(X_test)
    accuracy_ada = accuracy_score(y_test, y_pred_ada)
    end_time = time.time()

    # 3. LƯU MÔ HÌNH VÀO GOOGLE DRIVE
    model_path_ada = os.path.join(model_save_directory, "model_adaboost.joblib")
    joblib.dump(model_ada, model_path_ada)
    print(f"\nĐÃ LƯU MÔ HÌNH tại: {model_path_ada}")

    # 4. Lưu kết quả
    results.append({
        'Thuật toán': 'AdaBoost (Lọc)',
        'Độ chính xác (Accuracy)': accuracy_ada,
        'Thời gian (giây)': end_time - start_time
    })

    print(f"-> AdaBoost - Độ chính xác: {accuracy_ada*100:.2f}% (Thời gian: {end_time - start_time:.2f}s)")

    # 5. In Báo cáo Chi tiết
    print("\n--- Báo cáo Chi tiết (Classification Report) ---")
    print(classification_report(y_test, y_pred_ada, target_names=class_names))

    # 6. Vẽ Ma trận Nhầm lẫn
    print("\n--- Ma trận Nhầm lẫn (Confusion Matrix) ---")
    ConfusionMatrixDisplay.from_estimator(model_ada, X_test, y_test,
                                          display_labels=class_names,
                                          cmap=plt.cm.RdPu)
    plt.title('Ma trận Nhầm lẫn - AdaBoost')
    plt.show()

    # 7. VẼ ĐƯỜNG CONG HỌC TẬP (Learning Curve)
    print("\n--- Đường cong Học tập (Learning Curve) ---")

    train_sizes, train_scores, test_scores = learning_curve(
        model_ada, X_train, y_train, cv=3, n_jobs=-1, # Giảm cv xuống 3 cho nhanh
        train_sizes=np.linspace(.1, 1.0, 5)
    )

    train_scores_mean = np.mean(train_scores, axis=1)
    train_scores_std = np.std(train_scores, axis=1)
    test_scores_mean = np.mean(test_scores, axis=1)
    test_scores_std = np.std(test_scores, axis=1)

    plt.figure(figsize=(10, 6))
    plt.fill_between(train_sizes, train_scores_mean - train_scores_std,
                     train_scores_mean + train_scores_std, alpha=0.1, color="r")
    plt.fill_between(train_sizes, test_scores_mean - test_scores_std,
                     test_scores_mean + test_scores_std, alpha=0.1, color="g")

    plt.plot(train_sizes, train_scores_mean, 'o-', color="r", label="Điểm Huấn luyện (Train)")
    plt.plot(train_sizes, test_scores_mean, 'o-', color="g", label="Điểm Kiểm tra (Test)")

    plt.title("Đường cong Học tập - AdaBoost")
    plt.xlabel("Số lượng Mẫu Huấn luyện")
    plt.ylabel("Điểm Accuracy")
    plt.legend(loc="best")
    plt.grid(True)
    plt.show()

else:
    print("LỖI: Bạn cần chạy Bước 4.1 và 4.2 để tạo X_train, y_train trước.")

if 'explainer' in locals() and 'model_ada' in locals():
    sample_index = 10
    sample_data_row = X_test[sample_index]

    print(f"--- Bắt đầu Giải thích LIME cho Khách hàng thứ {sample_index} ---")

    explanation = explainer.explain_instance(
        data_row=sample_data_row,
        predict_fn=model_ada.predict_proba, # Dùng hàm .predict_proba
        num_features=10
    )

    actual_result = y_test.iloc[sample_index]
    print(f"Kết quả THỰC TẾ:      {class_names[actual_result]}")
    prediction = model_ada.predict([sample_data_row])[0]
    print(f"Dự đoán của MÔ HÌNH: {class_names[prediction]}")

    print("\n--- Lý do (Giải thích của LIME) ---")
    explanation.show_in_notebook(show_table=True, show_all=False)

else:
    print("LỖI: 'explainer' hoặc 'model_ada' chưa được tạo.")

"""##Thuật toán 7: Gradient Boosting"""

if 'X_train' in locals():
    print("--- 7. Đang huấn luyện: Gradient Boosting (GBM) ---")
    start_time = time.time()

    # 1. Khởi tạo và Huấn luyện
    model_gbm = GradientBoostingClassifier(random_state=42)
    model_gbm.fit(X_train, y_train)

    # 2. DỰ ĐOÁN VÀ ĐÁNH GIÁ
    y_pred_gbm = model_gbm.predict(X_test)
    accuracy_gbm = accuracy_score(y_test, y_pred_gbm)
    end_time = time.time()

    # 3. LƯU MÔ HÌNH VÀO GOOGLE DRIVE
    model_path_gbm = os.path.join(model_save_directory, "model_gradient_boosting.joblib")
    joblib.dump(model_gbm, model_path_gbm)
    print(f"\nĐÃ LƯU MÔ HÌNH tại: {model_path_gbm}")

    # 4. Lưu kết quả
    results.append({
        'Thuật toán': 'Gradient Boosting (Lọc)',
        'Độ chính xác (Accuracy)': accuracy_gbm,
        'Thời gian (giây)': end_time - start_time
    })

    print(f"-> Gradient Boosting - Độ chính xác: {accuracy_gbm*100:.2f}% (Thời gian: {end_time - start_time:.2f}s)")

    # 5. In Báo cáo Chi tiết
    print("\n--- Báo cáo Chi tiết (Classification Report) ---")
    print(classification_report(y_test, y_pred_gbm, target_names=class_names))

    # 6. Vẽ Ma trận Nhầm lẫn
    print("\n--- Ma trận Nhầm lẫn (Confusion Matrix) ---")
    ConfusionMatrixDisplay.from_estimator(model_gbm, X_test, y_test,
                                          display_labels=class_names,
                                          cmap=plt.cm.YlOrBr)
    plt.title('Ma trận Nhầm lẫn - Gradient Boosting')
    plt.show()

    # 7. VẼ ĐƯỜNG CONG HỌC TẬP (Learning Curve)
    print("\n--- Đường cong Học tập (Learning Curve) ---")

    train_sizes, train_scores, test_scores = learning_curve(
        model_gbm, X_train, y_train, cv=3, n_jobs=-1, # Giảm cv xuống 3 cho nhanh
        train_sizes=np.linspace(.1, 1.0, 5)
    )

    train_scores_mean = np.mean(train_scores, axis=1)
    train_scores_std = np.std(train_scores, axis=1)
    test_scores_mean = np.mean(test_scores, axis=1)
    test_scores_std = np.std(test_scores, axis=1)

    plt.figure(figsize=(10, 6))
    plt.fill_between(train_sizes, train_scores_mean - train_scores_std,
                     train_scores_mean + train_scores_std, alpha=0.1, color="r")
    plt.fill_between(train_sizes, test_scores_mean - test_scores_std,
                     test_scores_mean + test_scores_std, alpha=0.1, color="g")

    plt.plot(train_sizes, train_scores_mean, 'o-', color="r", label="Điểm Huấn luyện (Train)")
    plt.plot(train_sizes, test_scores_mean, 'o-', color="g", label="Điểm Kiểm tra (Test)")

    plt.title("Đường cong Học tập - Gradient Boosting")
    plt.xlabel("Số lượng Mẫu Huấn luyện")
    plt.ylabel("Điểm Accuracy")
    plt.legend(loc="best")
    plt.grid(True)
    plt.show()

else:
    print("LỖI: Bạn cần chạy Bước 4.1 và 4.2 để tạo X_train, y_train trước.")

if 'explainer' in locals() and 'model_gbm' in locals():
    sample_index = 10
    sample_data_row = X_test[sample_index]

    print(f"--- Bắt đầu Giải thích LIME cho Khách hàng thứ {sample_index} ---")

    explanation = explainer.explain_instance(
        data_row=sample_data_row,
        predict_fn=model_gbm.predict_proba, # Dùng hàm .predict_proba
        num_features=10
    )

    actual_result = y_test.iloc[sample_index]
    print(f"Kết quả THỰC TẾ:      {class_names[actual_result]}")
    prediction = model_gbm.predict([sample_data_row])[0]
    print(f"Dự đoán của MÔ HÌNH: {class_names[prediction]}")

    print("\n--- Lý do (Giải thích của LIME) ---")
    explanation.show_in_notebook(show_table=True, show_all=False)

else:
    print("LỖI: 'explainer' hoặc 'model_gbm' chưa được tạo.")

"""##Thuật toán 8: LightGBM (LGBM)"""

if 'X_train' in locals():
    print("--- 8. Đang huấn luyện: LightGBM (LGBM) ---")
    start_time = time.time()

    # 1. Khởi tạo và Huấn luyện
    model_lgbm = lgb.LGBMClassifier(random_state=42, verbosity=-1)
    model_lgbm.fit(X_train, y_train)

    # 2. DỰ ĐOÁN VÀ ĐÁNH GIÁ
    y_pred_lgbm = model_lgbm.predict(X_test)
    accuracy_lgbm = accuracy_score(y_test, y_pred_lgbm)
    end_time = time.time()

    # 3. LƯU MÔ HÌNH VÀO GOOGLE DRIVE
    model_path_lgbm = os.path.join(model_save_directory, "model_lightgbm.joblib")
    joblib.dump(model_lgbm, model_path_lgbm)
    print(f"\nĐÃ LƯU MÔ HÌNH tại: {model_path_lgbm}")

    # 4. Lưu kết quả
    results.append({
        'Thuật toán': 'LightGBM (Lọc)',
        'Độ chính xác (Accuracy)': accuracy_lgbm,
        'Thời gian (giây)': end_time - start_time
    })

    print(f"-> LightGBM - Độ chính xác: {accuracy_lgbm*100:.2f}% (Thời gian: {end_time - start_time:.2f}s)")

    # 5. In Báo cáo Chi tiết
    print("\n--- Báo cáo Chi tiết (Classification Report) ---")
    print(classification_report(y_test, y_pred_lgbm, target_names=class_names))

    # 6. Vẽ Ma trận Nhầm lẫn
    print("\n--- Ma trận Nhầm lẫn (Confusion Matrix) ---")
    ConfusionMatrixDisplay.from_estimator(model_lgbm, X_test, y_test,
                                          display_labels=class_names,
                                          cmap=plt.cm.YlGn)
    plt.title('Ma trận Nhầm lẫn - LightGBM')
    plt.show()

    # 7. VẼ ĐƯỜNG CONG HỌC TẬP (Learning Curve)
    print("\n--- Đường cong Học tập (Learning Curve) ---")

    train_sizes, train_scores, test_scores = learning_curve(
        model_lgbm, X_train, y_train, cv=3, n_jobs=-1, # Giảm cv xuống 3 cho nhanh
        train_sizes=np.linspace(.1, 1.0, 5)
    )

    train_scores_mean = np.mean(train_scores, axis=1)
    train_scores_std = np.std(train_scores, axis=1)
    test_scores_mean = np.mean(test_scores, axis=1)
    test_scores_std = np.std(test_scores, axis=1)

    plt.figure(figsize=(10, 6))
    plt.fill_between(train_sizes, train_scores_mean - train_scores_std,
                     train_scores_mean + train_scores_std, alpha=0.1, color="r")
    plt.fill_between(train_sizes, test_scores_mean - test_scores_std,
                     test_scores_mean + test_scores_std, alpha=0.1, color="g")

    plt.plot(train_sizes, train_scores_mean, 'o-', color="r", label="Điểm Huấn luyện (Train)")
    plt.plot(train_sizes, test_scores_mean, 'o-', color="g", label="Điểm Kiểm tra (Test)")

    plt.title("Đường cong Học tập - LightGBM")
    plt.xlabel("Số lượng Mẫu Huấn luyện")
    plt.ylabel("Điểm Accuracy")
    plt.legend(loc="best")
    plt.grid(True)
    plt.show()

else:
    print("LỖI: Bạn cần chạy Bước 4.1 và 4.2 để tạo X_train, y_train trước.")

if 'explainer' in locals() and 'model_lgbm' in locals():
    sample_index = 10
    sample_data_row = X_test[sample_index]

    print(f"--- Bắt đầu Giải thích LIME cho Khách hàng thứ {sample_index} ---")

    explanation = explainer.explain_instance(
        data_row=sample_data_row,
        predict_fn=model_lgbm.predict_proba, # Dùng hàm .predict_proba
        num_features=10
    )

    actual_result = y_test.iloc[sample_index]
    print(f"Kết quả THỰC TẾ:      {class_names[actual_result]}")
    prediction = model_lgbm.predict([sample_data_row])[0]
    print(f"Dự đoán của MÔ HÌNH: {class_names[prediction]}")

    print("\n--- Lý do (Giải thích của LIME) ---")
    explanation.show_in_notebook(show_table=True, show_all=False)

else:
    print("LỖI: 'explainer' hoặc 'model_lgbm' chưa được tạo.")

"""##Thuật toán 9: Mạng Nơ-ron Đa lớp (MLP - Deep Learning)"""

# Import các thư viện Keras (TensorFlow)
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.optimizers import Adam
import joblib # Dùng để lưu các mô hình scikit-learn

if 'X_train' in locals():
    print("--- 9. Đang huấn luyện: Mạng Nơ-ron Đa lớp (MLP) ---")
    start_time = time.time()

    # 1. Lấy số lượng "dấu hiệu" (features)
    input_dim = X_train.shape[1]

    # 2. Xây dựng Kiến trúc "Mạnh mẽ"
    model_mlp = Sequential()
    model_mlp.add(Dense(128, input_dim=input_dim, activation='relu'))
    model_mlp.add(BatchNormalization())
    model_mlp.add(Dropout(0.3))
    model_mlp.add(Dense(64, activation='relu'))
    model_mlp.add(BatchNormalization())
    model_mlp.add(Dropout(0.2))
    model_mlp.add(Dense(1, activation='sigmoid')) # 1 nơ-ron (0 hoặc 1)

    # 3. Định nghĩa Optimizer
    optimizer = Adam(learning_rate=0.001)
    model_mlp.compile(optimizer=optimizer,
                      loss='binary_crossentropy',
                      metrics=['accuracy'])

    print("--- Cấu trúc Mô hình MLP ---")
    model_mlp.summary()

    # 4. Định nghĩa "Vệ sĩ" (EarlyStopping)
    early_stopper = EarlyStopping(
        monitor='val_loss', # Theo dõi loss trên tập Validation
        patience=5,         # Dừng lại nếu 5 epochs không cải thiện
        verbose=1,
        restore_best_weights=True # Giữ lại mô hình tốt nhất
    )

    # 5. Huấn luyện
    history_mlp = model_mlp.fit(
        X_train,
        y_train,
        epochs=50, # Huấn luyện tối đa 50 lượt, "vệ sĩ" sẽ dừng sớm
        batch_size=32,
        validation_split=0.2, # Dùng 20% dữ liệu train để "vệ sĩ" theo dõi
        callbacks=[early_stopper],
        verbose=1 # In ra tiến độ
    )

    # 6. ĐÁNH GIÁ
    loss, accuracy_mlp = model_mlp.evaluate(X_test, y_test)
    end_time = time.time()

    # 7. LƯU MÔ HÌNH VÀO GOOGLE DRIVE
    # Mô hình Keras nên được lưu ở định dạng .h5 (hoặc .keras)
    model_path_mlp = os.path.join(model_save_directory, "model_mlp.h5")
    model_mlp.save(model_path_mlp)
    print(f"\nĐÃ LƯU MÔ HÌNH tại: {model_path_mlp}")

    # 8. Lưu kết quả
    results.append({
        'Thuật toán': 'Mạng Nơ-ron (MLP) (Lọc)',
        'Độ chính xác (Accuracy)': accuracy_mlp,
        'Thời gian (giây)': end_time - start_time
    })

    print(f"\n-> Mạng Nơ-ron (MLP) - Độ chính xác: {accuracy_mlp*100:.2f}% (Thời gian: {end_time - start_time:.2f}s)")

else:
    print("LỖI: Bạn cần chạy Bước 4.1 và 4.2 để tạo X_train, y_train trước.")

if 'history_mlp' in locals():
    print("--- Biểu đồ Lịch sử Huấn luyện (Accuracy & Loss) của MLP ---")

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))

    # --- Biểu đồ 1: Accuracy ---
    ax1.plot(history_mlp.history['accuracy'], label='Accuracy Huấn luyện (Train)')
    ax1.plot(history_mlp.history['val_accuracy'], label='Accuracy Kiểm tra (Validation)')
    ax1.set_title('Lịch sử Accuracy của MLP')
    ax1.set_xlabel('Epoch (Lượt học)')
    ax1.set_ylabel('Accuracy')
    ax1.legend()
    ax1.grid(True)

    # --- Biểu đồ 2: Loss ---
    ax2.plot(history_mlp.history['loss'], label='Loss Huấn luyện (Train)')
    ax2.plot(history_mlp.history['val_loss'], label='Loss Kiểm tra (Validation)')
    ax2.set_title('Lịch sử Loss của MLP')
    ax2.set_xlabel('Epoch (Lượt học)')
    ax2.set_ylabel('Loss')
    ax2.legend()
    ax2.grid(True)

    plt.show()
else:
    print("LỖI: 'history_mlp' chưa được tạo. Vui lòng chạy cell 5.18.")

if 'model_mlp' in locals():
    print("--- Báo cáo Chi tiết (Classification Report) của MLP ---")

    # Lấy dự đoán (dạng 0/1)
    y_pred_proba_mlp = model_mlp.predict(X_test)
    y_pred_mlp = (y_pred_proba_mlp > 0.5).astype(int) # Chuyển xác suất > 0.5 thành 1

    print(classification_report(y_test, y_pred_mlp, target_names=class_names))

    print("\n--- Ma trận Nhầm lẫn (Confusion Matrix) của MLP ---")
    ConfusionMatrixDisplay.from_predictions(y_test, y_pred_mlp,
                                            display_labels=class_names,
                                            cmap=plt.cm.cividis)
    plt.title('Ma trận Nhầm lẫn - Mạng Nơ-ron (MLP)')
    plt.show()

else:
    print("LỖI: 'model_mlp' chưa được tạo. Vui lòng chạy cell 5.18.")

if 'explainer' in locals() and 'model_mlp' in locals():
    # 1. Tạo "Hàm bao bọc" (Wrapper) cho LIME
    # LIME cần đầu ra là (N, 2) [Prob(0), Prob(1)]
    # Keras MLP cho đầu ra là (N, 1) [Prob(1)]

    def predict_fn_mlp(x):
        # verbose=0 để Keras không in ra tiến độ
        prob_1 = model_mlp.predict(x, verbose=0)
        prob_0 = 1 - prob_1
        return np.hstack([prob_0, prob_1]) # Ghép [Prob(0), Prob(1)]

    # 2. Giải thích
    sample_index = 10
    sample_data_row = X_test[sample_index]

    print(f"--- Bắt đầu Giải thích LIME (MLP) cho Khách hàng thứ {sample_index} ---")

    explanation = explainer.explain_instance(
        data_row=sample_data_row,
        predict_fn=predict_fn_mlp, # Dùng hàm bao bọc
        num_features=10
    )

    actual_result = y_test.iloc[sample_index]
    print(f"Kết quả THỰC TẾ:      {class_names[actual_result]}")
    prediction = (model_mlp.predict(sample_data_row.reshape(1,-1), verbose=0) > 0.5).astype(int)[0][0]
    print(f"Dự đoán của MÔ HÌNH: {class_names[prediction]}")

    print("\n--- Lý do (Giải thích của LIME) ---")
    explanation.show_in_notebook(show_table=True, show_all=False)

else:
    print("LỖI: 'explainer' hoặc 'model_mlp' chưa được tạo.")

"""##Thuật toán 10: Mạng Tích chập 1D (1D-CNN)"""

if 'X_train' in locals():
    # Lấy số lượng "dấu hiệu" (features)
    n_features = X_train.shape[1]

    # Reshape từ (N, n_features) thành (N, n_features, 1)
    X_train_cnn = X_train.reshape(X_train.shape[0], n_features, 1)
    X_test_cnn = X_test.reshape(X_test.shape[0], n_features, 1)

    print(f"Đã reshape dữ liệu cho 1D-CNN:")
    print(f"X_train cũ: {X_train.shape}")
    print(f"X_train MỚI: {X_train_cnn.shape}")

    # KIỂM TRA DỮ LIỆU
    print("\n--- 3 Dòng Dữ liệu mẫu (X_train_cnn) ---")
    print(X_train_cnn[:3])
else:
    print("LỖI: 'X_train' chưa được tạo.")

# Import thêm các Layer cho CNN
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten

if 'X_train_cnn' in locals():
    print("--- 10. Đang huấn luyện: Mạng Tích chập 1D (1D-CNN) ---")
    start_time = time.time()

    # 1. Xây dựng Kiến trúc 1D-CNN
    model_cnn = Sequential()

    # Lớp Tích chập (quét) đầu tiên
    model_cnn.add(Conv1D(filters=32, kernel_size=3, activation='relu', input_shape=(n_features, 1)))
    model_cnn.add(MaxPooling1D(pool_size=2)) # Lớp gộp
    model_cnn.add(BatchNormalization())

    # Lớp Tích chập thứ hai
    model_cnn.add(Conv1D(filters=64, kernel_size=3, activation='relu'))
    model_cnn.add(MaxPooling1D(pool_size=2))

    # Lớp "Duỗi" (Flatten) để chuyển về 1D
    model_cnn.add(Flatten())

    # Các lớp Dense (MLP) giống như trên
    model_cnn.add(Dense(64, activation='relu'))
    model_cnn.add(Dropout(0.3))
    model_cnn.add(Dense(1, activation='sigmoid'))

    # 2. Compile
    model_cnn.compile(optimizer='adam',
                      loss='binary_crossentropy',
                      metrics=['accuracy'])

    print("--- Cấu trúc Mô hình 1D-CNN ---")
    model_cnn.summary()

    # 3. Định nghĩa "Vệ sĩ" (EarlyStopping)
    early_stopper_cnn = EarlyStopping(monitor='val_loss', patience=5, verbose=1, restore_best_weights=True)

    # 4. Huấn luyện (dùng X_train_cnn)
    history_cnn = model_cnn.fit(
        X_train_cnn,
        y_train,
        epochs=50,
        batch_size=32,
        validation_split=0.2,
        callbacks=[early_stopper_cnn],
        verbose=1
    )

    # 5. ĐÁNH GIÁ (dùng X_test_cnn)
    loss, accuracy_cnn = model_cnn.evaluate(X_test_cnn, y_test)
    end_time = time.time()

    # 6. LƯU MÔ HÌNH VÀO GOOGLE DRIVE
    model_path_cnn = os.path.join(model_save_directory, "model_1d_cnn.h5")
    model_cnn.save(model_path_cnn)
    print(f"\nĐÃ LƯU MÔ HÌNH tại: {model_path_cnn}")

    # 7. Lưu kết quả
    results.append({
        'Thuật toán': 'Mạng 1D-CNN (Lọc)',
        'Độ chính xác (Accuracy)': accuracy_cnn,
        'Thời gian (giây)': end_time - start_time
    })

    print(f"\n-> Mạng 1D-CNN - Độ chính xác: {accuracy_cnn*100:.2f}% (Thời gian: {end_time - start_time:.2f}s)")

else:
    print("LỖI: Bạn cần chạy cell 5.22 để tạo X_train_cnn trước.")

if 'history_cnn' in locals():
    print("--- Biểu đồ Lịch sử Huấn luyện (Accuracy & Loss) của 1D-CNN ---")

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))

    # --- Biểu đồ 1: Accuracy ---
    ax1.plot(history_cnn.history['accuracy'], label='Accuracy Huấn luyện (Train)')
    ax1.plot(history_cnn.history['val_accuracy'], label='Accuracy Kiểm tra (Validation)')
    ax1.set_title('Lịch sử Accuracy của 1D-CNN')
    ax1.set_xlabel('Epoch (Lượt học)')
    ax1.set_ylabel('Accuracy')
    ax1.legend()
    ax1.grid(True)

    # --- Biểu đồ 2: Loss ---
    ax2.plot(history_cnn.history['loss'], label='Loss Huấn luyện (Train)')
    ax2.plot(history_cnn.history['val_loss'], label='Loss Kiểm tra (Validation)')
    ax2.set_title('Lịch sử Loss của 1D-CNN')
    ax2.set_xlabel('Epoch (Lượt học)')
    ax2.set_ylabel('Loss')
    ax2.legend()
    ax2.grid(True)

    plt.show()
else:
    print("LỖI: 'history_cnn' chưa được tạo. Vui lòng chạy cell 5.23.")

if 'model_cnn' in locals():
    print("--- Báo cáo Chi tiết (Classification Report) của 1D-CNN ---")

    # Lấy dự đoán (dạng 0/1)
    y_pred_proba_cnn = model_cnn.predict(X_test_cnn)
    y_pred_cnn = (y_pred_proba_cnn > 0.5).astype(int)

    print(classification_report(y_test, y_pred_cnn, target_names=class_names))

    print("\n--- Ma trận Nhầm lẫn (Confusion Matrix) của 1D-CNN ---")
    ConfusionMatrixDisplay.from_predictions(y_test, y_pred_cnn,
                                            display_labels=class_names,
                                            cmap=plt.cm.copper)
    plt.title('Ma trận Nhầm lẫn - Mạng 1D-CNN')
    plt.show()

else:
    print("LỖI: 'model_cnn' chưa được tạo. Vui lòng chạy cell 5.23.")

if 'explainer' in locals() and 'model_cnn' in locals():
    # 1. Tạo "Hàm bao bọc" (Wrapper) cho 1D-CNN
    # LIME sẽ đưa dữ liệu (N, n_features)
    # CNN cần (N, n_features, 1)

    def predict_fn_cnn(x):
        # Reshape dữ liệu 2D của LIME thành 3D cho CNN
        x_cnn = x.reshape(x.shape[0], n_features, 1)

        prob_1 = model_cnn.predict(x_cnn, verbose=0)
        prob_0 = 1 - prob_1
        return np.hstack([prob_0, prob_1])

    # 2. Giải thích
    sample_index = 10
    sample_data_row = X_test[sample_index] # Dùng X_test 2D gốc

    print(f"--- Bắt đầu Giải thích LIME (1D-CNN) cho Khách hàng thứ {sample_index} ---")

    explanation = explainer.explain_instance(
        data_row=sample_data_row,
        predict_fn=predict_fn_cnn, # Dùng hàm bao bọc CNN
        num_features=10
    )

    actual_result = y_test.iloc[sample_index]
    print(f"Kết quả THỰC TẾ:      {class_names[actual_result]}")
    prediction = (model_cnn.predict(sample_data_row.reshape(1,n_features,1), verbose=0) > 0.5).astype(int)[0][0]
    print(f"Dự đoán của MÔ HÌNH: {class_names[prediction]}")

    print("\n--- Lý do (Giải thích của LIME) ---")
    explanation.show_in_notebook(show_table=True, show_all=False)

else:
    print("LỖI: 'explainer' hoặc 'model_cnn' chưa được tạo.")

"""#Bước 6: Phân tích Mức độ Quan trọng của "Dấu hiệu" (Feature Importance)

##6.1. Tải mô hình LGBM và Trích xuất Mức độ Quan trọng
"""

import pandas as pd
import joblib
import os
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Tải lại mô hình LightGBM (đã lưu ở Bước 5.16)
try:
    model_path_lgbm = os.path.join(model_save_directory, "model_lightgbm.joblib")
    model_lgbm = joblib.load(model_path_lgbm)

    # 2. Lấy danh sách tên "dấu hiệu" (từ Bước 5.1)
    if 'feature_names' in locals():
        # 3. Lấy điểm quan trọng
        importances = model_lgbm.feature_importances_

        # 4. Tạo DataFrame để xem
        df_importance = pd.DataFrame({
            'Feature': feature_names,
            'Importance': importances
        })

        # 5. Sắp xếp từ cao đến thấp
        df_importance_sorted = df_importance.sort_values(by='Importance', ascending=False)

        print("--- 20 'Dấu hiệu' (Features) Quan trọng nhất (theo LightGBM) ---")
        print(df_importance_sorted.head(20).to_string(index=False))

    else:
        print("LỖI: Biến 'feature_names' chưa được tạo. Vui lòng chạy lại cell 5.1.")

except FileNotFoundError:
    print(f"LỖI: Không tìm thấy tệp mô hình tại: {model_path_lgbm}")
    print("Vui lòng chạy lại toàn bộ Bước 5 (cell 5.16) để huấn luyện và lưu mô hình LGBM.")
except Exception as e:
    print(f"Đã xảy ra lỗi: {e}")

"""##6.2. Trực quan hóa 20 "Dấu hiệu" (Features) VIP nhất"""

if 'df_importance_sorted' in locals():
    # Lấy 20 hàng đầu tiên
    df_top20 = df_importance_sorted.head(20)

    plt.figure(figsize=(12, 10))
    sns.barplot(
        data=df_top20,
        x='Importance',
        y='Feature',
        palette='rocket'
    )
    plt.title('Top 20 "Dấu hiệu" Quan trọng nhất (Theo LightGBM)', fontsize=16)
    plt.xlabel('Điểm Quan trọng', fontsize=12)
    plt.ylabel('Tên "Dấu hiệu" (Feature)', fontsize=12)
    plt.show()

else:
    print("LỖI: Biến 'df_importance_sorted' chưa được tạo. Vui lòng chạy cell 6.1.")

"""#Bước 7: "Cú cuối" - Huấn luyện Mô hình "VIP" (Feature Selection)

##7.1. Lọc Dữ liệu (Tạo X_train_vip và X_test_vip)
"""

if 'df_importance_sorted' in locals() and 'feature_names' in locals():
    # 1. Lấy danh sách 20 tên "dấu hiệu" VIP
    vip_features_list = df_importance_sorted.head(20)['Feature'].tolist()

    # 2. Lấy danh sách TẤT CẢ tên "dấu hiệu" (từ Bước 5.1)
    all_features_list = list(feature_names)

    # 3. Tìm VỊ TRÍ (indices) của các "dấu hiệu" VIP
    try:
        vip_indices = [all_features_list.index(name) for name in vip_features_list]
        print(f"Đã tìm thấy {len(vip_indices)} vị trí của 'dấu hiệu' VIP.")

        # 4. "Cắt" (Slice) các mảng X_train và X_test
        X_train_vip = X_train[:, vip_indices]
        X_test_vip = X_test[:, vip_indices]

    except ValueError as e:
        print(f"LỖI: Không tìm thấy tên 'dấu hiệu' trong danh sách. Lỗi: {e}")
        print("Điều này có thể xảy ra nếu 'feature_names' không khớp.")

else:
    print("LỖI: Biến 'df_importance_sorted' hoặc 'feature_names' chưa được tạo.")
    print("Vui lòng chạy lại Bước 5.1 và Bước 6.1.")

"""##7.2. (MỚI) Kiểm tra Dữ liệu Huấn luyện "VIP"
"""

if 'X_train_vip' in locals():
    print("--- KIỂM TRA DỮ LIỆU HUẤN LUYỆN 'VIP' ---")

    # 1. In Shape
    print(f"Shape của X_train (CŨ): {X_train.shape}")
    print(f"Shape của X_train_vip (MỚI): {X_train_vip.shape}")
    print(f"Shape của y_train (Không đổi): {y_train.shape}")

    # 2. In Dữ liệu mẫu
    print("\n--- 3 Dòng Dữ liệu mẫu (X_train_vip) ---")
    print("(Lưu ý: Dữ liệu này đã được lọc từ mảng 80+ cột)")
    print(X_train_vip[:3])

else:
    print("LỖI: Biến 'X_train_vip' chưa được tạo. Vui lòng chạy cell 7.1.")

"""##7.3. Huấn luyện lại Mạng Nơ-ron (MLP) "Mạnh mẽ" trên Dữ liệu VIP"""

if 'X_train_vip' in locals():
    print("--- 7.3. Đang huấn luyện MLP trên 20 'Dấu hiệu' VIP ---")
    start_time = time.time()

    # 1. Lấy số lượng "dấu hiệu" (features) MỚI
    input_dim_vip = X_train_vip.shape[1] # Sẽ là 20

    # 2. Xây dựng Kiến trúc (Y HỆT NHƯ CŨ - Cell 5.18)
    model_mlp_vip = Sequential()
    # Chỉ thay đổi input_dim
    model_mlp_vip.add(Dense(128, input_dim=input_dim_vip, activation='relu'))
    model_mlp_vip.add(BatchNormalization())
    model_mlp_vip.add(Dropout(0.3))
    model_mlp_vip.add(Dense(64, activation='relu'))
    model_mlp_vip.add(BatchNormalization())
    model_mlp_vip.add(Dropout(0.2))
    model_mlp_vip.add(Dense(1, activation='sigmoid'))

    # 3. Compile (Y HỆT NHƯ CŨ)
    optimizer = Adam(learning_rate=0.001)
    model_mlp_vip.compile(optimizer=optimizer,
                          loss='binary_crossentropy',
                          metrics=['accuracy'])

    print("--- Cấu trúc Mô hình MLP (VIP) ---")
    model_mlp_vip.summary() # Bạn sẽ thấy input_shape là (None, 20)

    # 4. Định nghĩa "Vệ sĩ" (EarlyStopping)
    early_stopper_vip = EarlyStopping(
        monitor='val_loss',
        patience=5,
        verbose=1,
        restore_best_weights=True
    )

    # 5. Huấn luyện (Dùng X_train_vip)
    history_mlp_vip = model_mlp_vip.fit(
        X_train_vip, # <-- Dùng dữ liệu VIP
        y_train,
        epochs=50,
        batch_size=32,
        validation_split=0.2,
        callbacks=[early_stopper_vip],
        verbose=1
    )

    # 6. ĐÁNH GIÁ (Dùng X_test_vip)
    loss_vip, accuracy_vip = model_mlp_vip.evaluate(X_test_vip, y_test)
    end_time = time.time()

    # 7. LƯU MÔ HÌNH VIP NÀY
    model_path_mlp_vip = os.path.join(model_save_directory, "model_mlp_VIP_Best.h5")
    model_mlp_vip.save(model_path_mlp_vip)
    print(f"\nĐÃ LƯU MÔ HÌNH VIP tại: {model_path_mlp_vip}")

    # 8. Lưu kết quả
    results.append({
        'Thuật toán': 'MLP (20 Dấu hiệu VIP)',
        'Độ chính xác (Accuracy)': accuracy_vip,
        'Thời gian (giây)': end_time - start_time
    })

    print(f"\n-> MLP (VIP) - Độ chính xác: {accuracy_vip*100:.2f}% (Thời gian: {end_time - start_time:.2f}s)")

else:
    print("LỖI: Bạn cần chạy cell 7.1 và 7.2 để tạo X_train_vip trước.")

"""##7.4. So sánh Kết quả Cuối cùng: (MLP All vs MLP VIP)"""

if 'accuracy_vip' in locals() and 'accuracy_mlp' in locals():

    print("--- 🏁 SO SÁNH KẾT QUẢ 'CÚ CUỐI' 🏁 ---")

    # Lấy accuracy của mô hình MLP cũ (từ Bước 5.18)
    print(f"Mô hình MLP (Tất cả 80+ 'dấu hiệu'): {accuracy_mlp*100:.2f}%")
    print(f"Mô hình MLP (Chỉ 20 'dấu hiệu' VIP): {accuracy_vip*100:.2f}%")

    if accuracy_vip > accuracy_mlp:
        print("\n🏆 THÀNH CÔNG! Bằng cách loại bỏ 'nhiễu', mô hình đã TỐT HƠN!")
        print("Mô hình 'model_mlp_VIP_Best.h5' là mô hình tốt nhất của bạn.")
    elif accuracy_vip == accuracy_mlp:
        print("\nỔN! Mô hình VIP hoạt động tốt NGANG BẰNG mô hình cũ, nhưng đơn giản và nhanh hơn.")
    else:
        print("\nTiếc quá! Mô hình cũ (dùng tất cả 'dấu hiệu') vẫn tốt hơn.")
        print("Điều này có nghĩa là các 'dấu hiệu' (features) yếu vẫn đóng góp một phần thông tin.")

else:
    print("LỖI: Biến 'accuracy_vip' hoặc 'accuracy_mlp' chưa được tạo.")
    print("Vui lòng chạy lại cell 5.18 và 7.3.")

"""#Bước 8: Tổng kết Bảng xếp hạng

##8.1. Hiển thị Bảng kết quả
"""

if 'results' in locals() and results:
    # 1. Chuyển kết quả (list of dictionaries) sang DataFrame
    results_df = pd.DataFrame(results)

    # 2. Sắp xếp theo Độ chính xác (cao nhất xuống thấp nhất)
    results_df = results_df.sort_values(by='Độ chính xác (Accuracy)', ascending=False)

    # 3. Định dạng lại cột Accuracy
    results_df['Độ chính xác (%)'] = results_df['Độ chính xác (Accuracy)'].apply(lambda x: f"{x*100:.2f}%")
    results_df['Thời gian (s)'] = results_df['Thời gian (giây)'].apply(lambda x: f"{x:.2f}s")

    print("--- 🏆 BẢNG XẾP HẠNG CUỐI CÙNG 🏆 ---")

    # In ra dạng bảng đẹp (dùng .to_string() để căn lề)
    print(results_df[['Thuật toán', 'Độ chính xác (%)', 'Thời gian (s)']].to_string(index=False))

else:
    print("LỖI: Biến 'results' chưa được tạo.")
    print("Vui lòng chạy lại các cell ở Bước 3 và Bước 5 để thu thập kết quả.")

"""logistic
mlp
svm
gradient boosting
randomforest

##8.2. Biểu đồ So sánh Trực quan
"""

if 'results_df' in locals():
    print("--- Biểu đồ So sánh Độ chính xác 10+ Thuật toán ---")

    # 1. Lấy lại DataFrame gốc (với số thập phân) để vẽ biểu đồ
    results_df_numeric = pd.DataFrame(results).sort_values(by='Độ chính xác (Accuracy)', ascending=False)

    # 2. Vẽ biểu đồ
    plt.figure(figsize=(12, 8))
    sns.barplot(
        data=results_df_numeric,
        x='Độ chính xác (Accuracy)',
        y='Thuật toán',
        palette='viridis' # Dùng dải màu "viridis"
    )

    plt.title('So sánh Độ chính xác của 10+ Thuật toán', fontsize=16)
    plt.xlabel('Độ chính xác (Accuracy)', fontsize=12)
    plt.ylabel('Thuật toán', fontsize=12)

    # Phóng to vào khoảng kết quả
    min_acc = results_df_numeric['Độ chính xác (Accuracy)'].min()
    max_acc = results_df_numeric['Độ chính xác (Accuracy)'].max()
    plt.xlim(min_acc * 0.95, max_acc * 1.05)

    # Thêm nhãn số % vào cuối mỗi thanh
    for index, row in results_df_numeric.iterrows():
        plt.text(row['Độ chính xác (Accuracy)'] + 0.002, # Vị trí
                 index, # Vị trí
                 f"{row['Độ chính xác (Accuracy)']*100:.2f}%", # Văn bản
                 color='black',
                 ha="left",
                 va="center")

    plt.show()

else:
    print("LỖI: Biến 'results_df' chưa được tạo. Vui lòng chạy cell 8.1 trước.")